# Generated by Django 6.0.4 on 2026-05-20 10:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_organisation'),
        ('payments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='abonnementeleve',
            constraint=models.UniqueConstraint(condition=models.Q(('statut', 'actif')), fields=('eleve', 'plan'), name='unique_abonnement_actif'),
        ),
    ]
