# Generated by Django 5.2.13 on 2026-05-14 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='abonnementeleve',
            unique_together=set(),
        ),
    ]
