# Generated by Django 6.0.4 on 2026-05-20 17:41

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_abonnementeleve_unique_abonnement_actif'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayoutCorrectionUnitaire',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('beneficiaire', models.CharField(choices=[('dev1', 'Développeur 1'), ('dev2', 'Développeur 2'), ('entretien', 'Entretien plateforme'), ('prof', 'Professeur')], max_length=20)),
                ('telephone', models.CharField(max_length=20)),
                ('montant', models.DecimalField(decimal_places=0, max_digits=12)),
                ('taux_applique', models.DecimalField(decimal_places=2, max_digits=5)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('envoye', 'Envoyé'), ('succes', 'Succès'), ('echec', 'Échec')], default='en_attente', max_length=20)),
                ('fedapay_payout_id', models.CharField(blank=True, max_length=100)),
                ('reponse_api', models.JSONField(blank=True, null=True)),
                ('message_erreur', models.TextField(blank=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_traitement', models.DateTimeField(blank=True, null=True)),
                ('paiement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payouts', to='payments.paiementcorrectionunitaire')),
            ],
            options={
                'verbose_name': 'Payout correction unitaire',
                'verbose_name_plural': 'Payouts correction unitaire',
                'ordering': ['-date_creation'],
            },
        ),
    ]
