# Generated by Django 5.2.13 on 2026-05-15 11:00

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_alter_abonnementeleve_unique_together'),
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigurationCommission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('taux_admin', models.DecimalField(decimal_places=2, default=10, max_digits=5, verbose_name='taux admin (%)')),
                ('taux_commercial', models.DecimalField(decimal_places=2, default=20, max_digits=5, verbose_name='taux commercial (%)')),
                ('taux_prestataire', models.DecimalField(decimal_places=2, default=70, max_digits=5, verbose_name='taux prestataire (%)')),
                ('telephone_admin', models.CharField(max_length=20, verbose_name='téléphone admin')),
                ('telephone_commercial', models.CharField(max_length=20, verbose_name='téléphone commercial')),
                ('telephone_prestataire', models.CharField(max_length=20, verbose_name='téléphone prestataire')),
                ('is_actif', models.BooleanField(default=True, verbose_name='actif')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('etablissement', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='config_commission', to='schools.etablissement')),
            ],
            options={
                'verbose_name': 'Configuration commission',
                'verbose_name_plural': 'Configurations commission',
            },
        ),
        migrations.CreateModel(
            name='PayoutCommission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('beneficiaire', models.CharField(choices=[('admin', 'Admin'), ('commercial', 'Commercial'), ('prestataire', 'Prestataire')], max_length=20, verbose_name='bénéficiaire')),
                ('telephone', models.CharField(max_length=20, verbose_name='téléphone')),
                ('montant', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='montant (XOF)')),
                ('taux_applique', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='taux appliqué (%)')),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('envoye', 'Envoyé'), ('succes', 'Succès'), ('echec', 'Échec')], default='en_attente', max_length=20, verbose_name='statut')),
                ('fedapay_payout_id', models.CharField(blank=True, max_length=100, verbose_name='FedaPay Payout ID')),
                ('reponse_api', models.JSONField(blank=True, null=True, verbose_name='réponse API')),
                ('message_erreur', models.TextField(blank=True, verbose_name='erreur')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_traitement', models.DateTimeField(blank=True, null=True, verbose_name='date de traitement')),
                ('paiement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payouts', to='payments.paiementabonnement')),
            ],
            options={
                'verbose_name': 'Payout commission',
                'verbose_name_plural': 'Payouts commissions',
                'ordering': ['-date_creation'],
            },
        ),
    ]
