# Generated by Django 5.2.13 on 2026-05-15 11:27

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compositions', '0006_paywall_system'),
        ('payments', '0003_add_commission_payout_models'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaiementCorrectionUnitaire',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reference', models.CharField(max_length=100, unique=True, verbose_name='référence')),
                ('montant', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='montant (XOF)')),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('en_cours', 'En cours'), ('succes', 'Succès'), ('echec', 'Échec'), ('annule', 'Annulé')], default='en_attente', max_length=20, verbose_name='statut')),
                ('fedapay_transaction_id', models.CharField(blank=True, max_length=100, verbose_name='FedaPay Transaction ID')),
                ('fedapay_url_paiement', models.URLField(blank=True, verbose_name='URL de paiement')),
                ('fedapay_webhook_data', models.JSONField(blank=True, null=True, verbose_name='données webhook')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_paiement', models.DateTimeField(blank=True, null=True, verbose_name='date de paiement')),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paiements_corrections', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paiements_correction', to='compositions.compositionsession')),
            ],
            options={
                'verbose_name': 'Paiement correction unitaire',
                'verbose_name_plural': 'Paiements corrections unitaires',
                'ordering': ['-date_creation'],
            },
        ),
    ]
