# Generated by Django 6.0.4 on 2026-05-09 09:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_classe_niveau'),
        ('qcm', '0002_qcmresultat'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QCMBeninConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titre', models.CharField(max_length=300, verbose_name='titre')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('niveau', models.CharField(choices=[('primaire', 'Primaire'), ('college', "Collège - Cycle d'Orientation"), ('lycee', 'Lycée - Cycle Terminal'), ('superieur', 'Enseignement Supérieur'), ('concours', 'Concours et Examens')], max_length=20, verbose_name='niveau')),
                ('type_qcm', models.CharField(choices=[('evaluation', 'Évaluation Formative'), ('examen', 'Examen Sommatif'), ('concours', 'Concours National'), ('revision', 'Révision et Soutien')], max_length=20, verbose_name='type')),
                ('langue', models.CharField(choices=[('fr', 'Français'), ('en', 'English'), ('es', 'Español'), ('ar', 'العربية')], default='fr', max_length=10, verbose_name='langue')),
                ('referentiel', models.JSONField(default=dict, help_text='Points du programme officiel béninois', verbose_name='référentiel programme')),
                ('objectifs_pedagogiques', models.JSONField(default=list, verbose_name='objectifs pédagogiques')),
                ('competences_visees', models.JSONField(default=list, verbose_name='compétences visées')),
                ('prompt_ia', models.TextField(blank=True, help_text="Instructions spécifiques pour l'IA", verbose_name='prompt IA personnalisé')),
                ('style_questions', models.JSONField(default=dict, help_text='Format et style des questions', verbose_name='style questions')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qcm_benin', to='core.classe')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qcm_crees', to=settings.AUTH_USER_MODEL)),
                ('matiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qcm_benin', to='core.matiere')),
            ],
            options={
                'verbose_name': 'QCM Bénin',
                'verbose_name_plural': 'QCMs Bénin',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QCMSessionBenin',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('statut', models.CharField(choices=[('commence', 'Commencé'), ('en_cours', 'En cours'), ('termine', 'Terminé'), ('abandonne', 'Abandonné')], default='commence', max_length=20, verbose_name='statut')),
                ('date_debut', models.DateTimeField(auto_now_add=True)),
                ('date_fin', models.DateTimeField(blank=True, null=True)),
                ('temps_total', models.PositiveIntegerField(help_text='Temps alloué pour le QCM', verbose_name='temps total (secondes)')),
                ('temps_restant', models.PositiveIntegerField(blank=True, null=True, verbose_name='temps restant')),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='score')),
                ('pourcentage', models.PositiveIntegerField(blank=True, null=True, verbose_name='pourcentage')),
                ('note', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='note sur 20')),
                ('reponses_correctes', models.PositiveIntegerField(default=0, verbose_name='réponses correctes')),
                ('reponses_incorrectes', models.PositiveIntegerField(default=0, verbose_name='réponses incorrectes')),
                ('reponses_non_repondues', models.PositiveIntegerField(default=0, verbose_name='non répondues')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qcm_sessions', to=settings.AUTH_USER_MODEL)),
                ('qcm_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='qcm.qcmbeninconfig')),
            ],
            options={
                'verbose_name': 'Session QCM',
                'verbose_name_plural': 'Sessions QCM',
                'ordering': ['-date_debut'],
            },
        ),
        migrations.CreateModel(
            name='QuestionBenin',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('enonce', models.TextField(verbose_name='énoncé')),
                ('type_question', models.CharField(choices=[('qcm', 'QCM Simple'), ('qcm_multiple', 'QCM à Choix Multiples'), ('vrai_faux', 'Vrai/Faux'), ('association', 'Association'), ('ordonnancement', 'Ordonnancement'), ('completion', 'Texte à compléter')], max_length=20, verbose_name='type')),
                ('numero', models.PositiveIntegerField(default=1, verbose_name='numéro')),
                ('chapitre', models.CharField(blank=True, max_length=200, verbose_name='chapitre')),
                ('lecon', models.CharField(blank=True, max_length=200, verbose_name='leçon')),
                ('competence', models.CharField(blank=True, max_length=300, verbose_name='compétence')),
                ('difficulte', models.CharField(choices=[('facile', 'Facile'), ('moyen', 'Moyen'), ('difficile', 'Difficile')], default='moyen', max_length=10, verbose_name='difficulté')),
                ('points', models.PositiveIntegerField(default=1, verbose_name='points')),
                ('temps_estime', models.PositiveIntegerField(default=60, verbose_name='temps estimé (secondes)')),
                ('explication', models.TextField(blank=True, help_text='Explication détaillée de la réponse', verbose_name='explication')),
                ('references', models.JSONField(default=list, help_text='Références du programme ou manuels', verbose_name='références')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('qcm_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='qcm.qcmbeninconfig')),
            ],
            options={
                'verbose_name': 'Question Bénin',
                'verbose_name_plural': 'Questions Bénin',
                'ordering': ['qcm_config', 'numero'],
                'unique_together': {('qcm_config', 'numero')},
            },
        ),
        migrations.CreateModel(
            name='ChoixBenin',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('texte', models.TextField(verbose_name='texte du choix')),
                ('est_correct', models.BooleanField(default=False, verbose_name='est correct')),
                ('ordre', models.PositiveIntegerField(default=1, verbose_name='ordre')),
                ('feedback_si_choisi', models.TextField(blank=True, help_text="Explication si l'élève choisit cette option", verbose_name='feedback si choisi')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choix', to='qcm.questionbenin')),
            ],
            options={
                'verbose_name': 'Choix QCM',
                'verbose_name_plural': 'Choix QCM',
                'ordering': ['ordre'],
            },
        ),
        migrations.CreateModel(
            name='ReponseQCMBenin',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reponse', models.JSONField(help_text='Format selon le type de question', verbose_name='réponse')),
                ('est_correct', models.BooleanField(default=False, verbose_name='est correct')),
                ('temps_reponse', models.PositiveIntegerField(blank=True, null=True, verbose_name='temps de réponse (secondes)')),
                ('feedback_ia', models.TextField(blank=True, verbose_name='feedback IA')),
                ('points_obtenus', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='points obtenus')),
                ('reponse_at', models.DateTimeField(auto_now_add=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reponses', to='qcm.questionbenin')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reponses', to='qcm.qcmsessionbenin')),
            ],
            options={
                'verbose_name': 'Réponse QCM',
                'verbose_name_plural': 'Réponses QCM',
                'unique_together': {('session', 'question')},
            },
        ),
    ]
