# Generated by Django 6.0.4 on 2026-05-04 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classe',
            name='niveau',
            field=models.CharField(choices=[('primaire', 'Primaire'), ('secondaire', 'Secondaire'), ('universitaire', 'Universitaire'), ('professionnel', 'Formation Professionnelle')], max_length=20, verbose_name='niveau'),
        ),
    ]
