# Generated by Django 5.2.13 on 2026-05-20 09:46

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_classe_niveau'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organisation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=200, verbose_name='nom')),
                ('code', models.CharField(max_length=30, unique=True, verbose_name='code')),
                ('pays', models.CharField(default='Bénin', max_length=100, verbose_name='pays')),
                ('devise', models.CharField(default='XOF', max_length=10, verbose_name='devise')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='organisations/logos/', verbose_name='logo')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('is_active', models.BooleanField(default=True, verbose_name='actif')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'organisation',
                'verbose_name_plural': 'organisations',
                'ordering': ['nom'],
            },
        ),
    ]
