# Generated by Django 6.0.4 on 2026-05-11 07:09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0003_alter_classe_niveau'),
        ('schools', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamenSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type_examen', models.CharField(choices=[('cepe', "CEPE - Certificat d'Études Primaires"), ('bepc', "BEPC - Brevet d'Études du Premier Cycle"), ('bac', 'Baccalauréat'), ('concours', "Concours d'entrée"), ('examen_blanc', 'Examen Blanc'), ('devoir', 'Devoir de Contrôle')], max_length=20, verbose_name="type d'examen")),
                ('session', models.CharField(choices=[('principale', 'Session Principale'), ('rattrapage', 'Session de Rattrapage'), ('remplacement', 'Session de Remplacement')], default='principale', max_length=20, verbose_name='session')),
                ('annee_scolaire', models.CharField(default='2024-2025', max_length=9, verbose_name='année scolaire')),
                ('date_debut', models.DateField(verbose_name='date de début')),
                ('date_fin', models.DateField(verbose_name='date de fin')),
                ('date_publication_resultats', models.DateField(blank=True, null=True, verbose_name='date de publication des résultats')),
                ('moyenne_admission', models.DecimalField(decimal_places=2, default=10.0, max_digits=5, verbose_name="moyenne d'admission")),
                ('nombre_inscrits', models.PositiveIntegerField(default=0, verbose_name="nombre d'inscrits")),
                ('nombre_admis', models.PositiveIntegerField(default=0, verbose_name="nombre d'admis")),
                ('nombre_refuses', models.PositiveIntegerField(default=0, verbose_name='nombre de refusés')),
                ('taux_reussite', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='taux de réussite (%)')),
                ('is_ouvert', models.BooleanField(default=True, verbose_name='ouvert aux inscriptions')),
                ('is_termine', models.BooleanField(default=False, verbose_name='terminé')),
                ('resultats_publies', models.BooleanField(default=False, verbose_name='résultats publiés')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('instructions', models.TextField(blank=True, verbose_name='instructions')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('etablissement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examens_sessions', to='schools.etablissement')),
                ('matieres', models.ManyToManyField(related_name='examens_sessions', to='core.matiere')),
            ],
            options={
                'verbose_name': "Session d'examen",
                'verbose_name_plural': "Sessions d'examens",
                'ordering': ['-date_debut'],
            },
        ),
        migrations.CreateModel(
            name='CertificatScolaire',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('numero_certificat', models.CharField(max_length=50, unique=True, verbose_name='numéro de certificat')),
                ('annee_scolaire', models.CharField(default='2024-2025', max_length=9, verbose_name='année scolaire')),
                ('session', models.CharField(default='Session Principale', max_length=20, verbose_name='session')),
                ('moyenne_generale', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='moyenne générale')),
                ('note_maximale', models.DecimalField(decimal_places=2, default=20.0, max_digits=5, verbose_name='note maximale')),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('admis', 'Admis'), ('refuse', 'Refusé'), ('passable', 'Passable'), ('assez_bien', 'Assez Bien'), ('bien', 'Bien'), ('tres_bien', 'Très Bien')], default='en_attente', max_length=20, verbose_name='statut')),
                ('est_delivre', models.BooleanField(default=False, verbose_name='délivré')),
                ('mention', models.CharField(blank=True, max_length=50, verbose_name='mention')),
                ('intitule_programme', models.CharField(blank=True, max_length=200, verbose_name='intitulé du programme')),
                ('appreciation_generale', models.TextField(blank=True, verbose_name='appréciation générale')),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='certificats/qr_codes/', verbose_name='QR code')),
                ('code_verification', models.CharField(blank=True, max_length=20, verbose_name='code de vérification')),
                ('date_signature_1', models.DateField(blank=True, null=True, verbose_name='date de signature 1')),
                ('date_signature_2', models.DateField(blank=True, null=True, verbose_name='date de signature 2')),
                ('lieu_delivrance', models.CharField(default='Cotonou', max_length=100, verbose_name='lieu de délivrance')),
                ('date_delivrance', models.DateField(blank=True, null=True, verbose_name='date de délivrance')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificats', to='schools.classe')),
                ('delivre_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certificats_delivres', to=settings.AUTH_USER_MODEL)),
                ('eleve', models.ForeignKey(limit_choices_to={'role': 'eleve'}, on_delete=django.db.models.deletion.CASCADE, related_name='certificats_scolaires', to=settings.AUTH_USER_MODEL)),
                ('etablissement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificats', to='schools.etablissement')),
                ('signataire_1', models.ForeignKey(blank=True, limit_choices_to={'role__in': ['admin', 'professeur']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certificats_signes_1', to=settings.AUTH_USER_MODEL)),
                ('signataire_2', models.ForeignKey(blank=True, limit_choices_to={'role__in': ['admin', 'professeur']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certificats_signes_2', to=settings.AUTH_USER_MODEL)),
                ('examen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='certificats', to='certificats.examensession')),
            ],
            options={
                'verbose_name': 'Certificat scolaire',
                'verbose_name_plural': 'Certificats scolaires',
                'ordering': ['-date_delivrance', 'eleve__last_name'],
            },
        ),
        migrations.CreateModel(
            name='HistoriqueCertificat',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code_verification', models.CharField(max_length=20, verbose_name='code de vérification utilisé')),
                ('resultat_verification', models.BooleanField(verbose_name='résultat de la vérification')),
                ('ip_verificateur', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP du vérificateur')),
                ('date_verification', models.DateTimeField(auto_now_add=True, verbose_name='date de vérification')),
                ('certificat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historique_verifications', to='certificats.certificatscolaire')),
            ],
            options={
                'verbose_name': 'Historique de vérification',
                'verbose_name_plural': 'Historiques de vérifications',
                'ordering': ['-date_verification'],
            },
        ),
        migrations.CreateModel(
            name='InscriptionExamen',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('numero_inscription', models.CharField(max_length=50, unique=True, verbose_name="numéro d'inscription")),
                ('date_inscription', models.DateField(auto_now_add=True, verbose_name="date d'inscription")),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('confirmee', 'Confirmée'), ('annulee', 'Annulée')], default='en_attente', max_length=20, verbose_name='statut')),
                ('moyenne_obtenue', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='moyenne obtenue')),
                ('est_admis', models.BooleanField(blank=True, null=True, verbose_name='admis')),
                ('decision_jury', models.CharField(blank=True, max_length=50, verbose_name='décision du jury')),
                ('observations', models.TextField(blank=True, verbose_name='observations')),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscriptions_examens', to='schools.classe')),
                ('eleve', models.ForeignKey(limit_choices_to={'role': 'eleve'}, on_delete=django.db.models.deletion.CASCADE, related_name='inscriptions_examens', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscriptions', to='certificats.examensession')),
            ],
            options={
                'verbose_name': "Inscription à l'examen",
                'verbose_name_plural': 'Inscriptions aux examens',
                'unique_together': {('session', 'eleve')},
            },
        ),
        migrations.CreateModel(
            name='TypeCertificat',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='code')),
                ('nom', models.CharField(max_length=200, verbose_name='nom')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('niveau_scolaire', models.CharField(choices=[('primaire', 'Enseignement Primaire'), ('secondaire_1', '1er Cycle Secondaire'), ('secondaire_2', '2nd Cycle Secondaire'), ('universitaire', 'Universitaire'), ('professionnel', 'Formation Professionnelle')], max_length=20, verbose_name='niveau scolaire')),
                ('mention_reussite', models.CharField(default='ADMIS', max_length=50, verbose_name='mention de réussite')),
                ('mention_echec', models.CharField(default='REFUSÉ', max_length=50, verbose_name="mention d'échec")),
                ('template_fond', models.ImageField(blank=True, null=True, upload_to='certificats/templates/', verbose_name='template de fond')),
                ('couleur_principale', models.CharField(default='#1e3a8a', max_length=7, verbose_name='couleur principale')),
                ('couleur_secondaire', models.CharField(default='#3b82f6', max_length=7, verbose_name='couleur secondaire')),
                ('titre_signataire_1', models.CharField(default='Le Directeur', max_length=100, verbose_name='titre signataire 1')),
                ('titre_signataire_2', models.CharField(default='Le Chef des Travaux', max_length=100, verbose_name='titre signataire 2')),
                ('is_actif', models.BooleanField(default=True, verbose_name='actif')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('etablissement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='types_certificats', to='schools.etablissement')),
            ],
            options={
                'verbose_name': 'Type de certificat',
                'verbose_name_plural': 'Types de certificats',
                'ordering': ['niveau_scolaire', 'nom'],
            },
        ),
        migrations.AddField(
            model_name='certificatscolaire',
            name='type_certificat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificats', to='certificats.typecertificat'),
        ),
        migrations.CreateModel(
            name='CopieExamenPhysique',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image_copie', models.ImageField(upload_to='examens/copies/', verbose_name='image de la copie')),
                ('images_supplementaires', models.JSONField(blank=True, null=True, verbose_name='images supplémentaires')),
                ('texte_extrait', models.TextField(blank=True, verbose_name='texte extrait (OCR)')),
                ('correction_ia', models.JSONField(blank=True, null=True, verbose_name='correction IA')),
                ('note_suggeree_ia', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name="note suggérée par l'IA")),
                ('note_finale', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='note finale')),
                ('appreciation', models.TextField(blank=True, verbose_name='appréciation')),
                ('annotations_correcteur', models.TextField(blank=True, verbose_name='annotations du correcteur')),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('en_cours', 'En cours de correction'), ('corrigee', 'Corrigée'), ('verifiee', 'Vérifiée'), ('annulee', 'Annulée')], default='en_attente', max_length=20, verbose_name='statut')),
                ('corrige_par_ia', models.BooleanField(default=False, verbose_name='corrigé par IA')),
                ('date_soumission', models.DateTimeField(auto_now_add=True, verbose_name='date de soumission')),
                ('date_correction_ia', models.DateTimeField(blank=True, null=True, verbose_name='date correction IA')),
                ('date_verification', models.DateTimeField(blank=True, null=True, verbose_name='date de vérification')),
                ('matiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='copies_examens', to='core.matiere')),
                ('verifie_par', models.ForeignKey(blank=True, limit_choices_to={'role': 'professeur'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='copies_verifiees', to=settings.AUTH_USER_MODEL)),
                ('inscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='copies', to='certificats.inscriptionexamen')),
            ],
            options={
                'verbose_name': "Copie d'examen physique",
                'verbose_name_plural': "Copies d'examens physiques",
                'unique_together': {('inscription', 'matiere')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='certificatscolaire',
            unique_together={('eleve', 'type_certificat', 'annee_scolaire')},
        ),
    ]
