# Generated by Django 6.0.4 on 2026-05-11 07:09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schools', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IndicateurPerformance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100, verbose_name='nom')),
                ('type_indicateur', models.CharField(choices=[('taux_reussite', 'Taux de réussite'), ('moyenne_generale', 'Moyenne générale'), ('taux_presence', 'Taux de présence'), ('taux_paiement', 'Taux de paiement'), ('taux_abandon', "Taux d'abandon"), ('taux_redoublement', 'Taux de redoublement')], max_length=30, verbose_name='type')),
                ('valeur_actuelle', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='valeur actuelle')),
                ('valeur_cible', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='valeur cible')),
                ('periode', models.CharField(max_length=20, verbose_name='période')),
                ('date_calcul', models.DateTimeField(auto_now=True, verbose_name='date de calcul')),
                ('etablissement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indicateurs', to='schools.etablissement')),
            ],
            options={
                'verbose_name': 'Indicateur',
                'verbose_name_plural': 'Indicateurs',
            },
        ),
        migrations.CreateModel(
            name='RapportStatistique',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type_rapport', models.CharField(choices=[('performance_eleves', 'Performance des élèves'), ('resultats_examens', 'Résultats des examens'), ('assiduite', 'Assiduité'), ('financier', 'Rapport financier'), ('pedagogique', 'Rapport pédagogique')], max_length=30, verbose_name='type')),
                ('titre', models.CharField(max_length=200, verbose_name='titre')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('periode_debut', models.DateField(verbose_name='début')),
                ('periode_fin', models.DateField(verbose_name='fin')),
                ('donnees', models.JSONField(verbose_name='données du rapport')),
                ('fichier_pdf', models.FileField(blank=True, null=True, upload_to='analytics/rapports/', verbose_name='rapport PDF')),
                ('date_generation', models.DateTimeField(auto_now_add=True)),
                ('etablissement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rapports_stats', to='schools.etablissement')),
                ('genere_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rapports_stats_generes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Rapport statistique',
                'verbose_name_plural': 'Rapports statistiques',
                'ordering': ['-date_generation'],
            },
        ),
        migrations.CreateModel(
            name='TableauBord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100, verbose_name='nom')),
                ('configuration', models.JSONField(default=dict, verbose_name='configuration des widgets')),
                ('is_defaut', models.BooleanField(default=False, verbose_name='tableau de bord par défaut')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tableaux_de_bord', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tableau de bord',
                'verbose_name_plural': 'Tableaux de bord',
            },
        ),
    ]
