# Generated by Django 6.0.4 on 2026-04-30 18:33

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Leaderboard',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('periode', models.CharField(choices=[('weekly', 'Hebdomadaire'), ('monthly', 'Mensuel'), ('trimestriel', 'Trimestriel'), ('alltime', 'Tous les temps')], default='alltime', max_length=20, verbose_name='période')),
                ('rank', models.IntegerField(default=0, verbose_name='rang')),
                ('score', models.IntegerField(default=0, verbose_name='score')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='dernière mise à jour')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_leaderboard_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'classement',
                'verbose_name_plural': 'classements',
                'ordering': ['periode', 'rank'],
                'unique_together': {('user', 'periode')},
            },
        ),
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code_parrainage', models.CharField(blank=True, max_length=20, unique=True, verbose_name='code de parrainage')),
                ('bonus_xp', models.IntegerField(default=100, verbose_name='bonus XP')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='date de parrainage')),
                ('is_active', models.BooleanField(default=True, verbose_name='actif')),
                ('filleul', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filleuls', to=settings.AUTH_USER_MODEL, verbose_name='filleul')),
                ('parrain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parrainages', to=settings.AUTH_USER_MODEL, verbose_name='parrain')),
            ],
            options={
                'verbose_name': 'parrainage',
                'verbose_name_plural': 'parrainages',
                'ordering': ['-created_at'],
                'unique_together': {('parrain', 'filleul')},
            },
        ),
    ]
