# Generated by Django 6.0.4 on 2026-05-01 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_leaderboard_referral'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='laravel_id',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True, verbose_name='ID Laravel'),
        ),
        migrations.AddField(
            model_name='user',
            name='laravel_token',
            field=models.TextField(blank=True, default='', verbose_name='Token Laravel'),
        ),
        migrations.AddField(
            model_name='user',
            name='xp',
            field=models.PositiveIntegerField(default=0, verbose_name='XP'),
        ),
        migrations.AlterField(
            model_name='user',
            name='niveau',
            field=models.CharField(choices=[('primaire', 'Primaire'), ('secondaire', 'Secondaire'), ('universitaire', 'Universitaire'), ('professionnel', 'Formation Professionnelle'), ('entreprise', 'Entreprise')], default='secondaire', max_length=30, verbose_name='niveau'),
        ),
    ]
