# Generated by Django 6.0.4 on 2026-05-02 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_laravel_id_user_laravel_token_user_xp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='sexe',
            field=models.CharField(blank=True, choices=[('Masculin', 'Masculin'), ('Féminin', 'Féminin')], default='', max_length=10, verbose_name='sexe'),
        ),
    ]
