# Generated by Django 5.2.13 on 2026-05-14 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_sexe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrateur'), ('conseiller', 'Conseiller Pédagogique'), ('professeur', 'Professeur'), ('eleve', 'Élève / Étudiant')], db_index=True, default='eleve', max_length=20, verbose_name='rôle'),
        ),
    ]
