# Generated by Django 6.0.4 on 2026-05-20 12:18

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_user_type_candidat'),
        ('core', '0004_organisation'),
    ]

    operations = [
        migrations.CreateModel(
            name='MembreOrganisation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('admin', 'Administrateur'), ('professeur', 'Professeur'), ('conseiller', 'Conseiller Pédagogique'), ('eleve', 'Élève / Étudiant')], default='eleve', max_length=20, verbose_name='rôle')),
                ('est_principal', models.BooleanField(default=False, help_text='Organisation affichée par défaut pour cet utilisateur', verbose_name='organisation principale')),
                ('date_adhesion', models.DateTimeField(auto_now_add=True, verbose_name="date d'adhésion")),
                ('is_active', models.BooleanField(default=True, verbose_name='actif')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membres', to='core.organisation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'membre organisation',
                'verbose_name_plural': 'membres organisation',
                'ordering': ['-est_principal', '-date_adhesion'],
                'unique_together': {('user', 'organisation')},
            },
        ),
    ]
