# Generated by Django 6.0.4 on 2026-05-22 18:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_membreorganisation'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfilEleve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_naissance', models.DateField(blank=True, null=True, verbose_name='date de naissance')),
                ('lieu_naissance', models.CharField(blank=True, max_length=200, verbose_name='lieu de naissance')),
                ('nationalite', models.CharField(blank=True, default='Béninoise', max_length=100, verbose_name='nationalité')),
                ('etablissement_origine', models.CharField(blank=True, max_length=200, verbose_name="établissement d'origine")),
                ('est_redoublant', models.BooleanField(default=False, verbose_name='redoublant')),
                ('nb_redoublements', models.PositiveSmallIntegerField(default=0, verbose_name='nombre de fois redoublé')),
                ('nom_pere', models.CharField(blank=True, max_length=200, verbose_name='nom et prénoms du père / tuteur')),
                ('profession_pere', models.CharField(blank=True, max_length=200, verbose_name='profession du père / tuteur')),
                ('telephone_pere', models.CharField(blank=True, max_length=30, verbose_name='téléphone du père / tuteur')),
                ('nom_mere', models.CharField(blank=True, max_length=200, verbose_name='nom et prénoms de la mère / tutrice')),
                ('profession_mere', models.CharField(blank=True, max_length=200, verbose_name='profession de la mère / tutrice')),
                ('telephone_mere', models.CharField(blank=True, max_length=30, verbose_name='téléphone de la mère / tutrice')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profil_eleve', to=settings.AUTH_USER_MODEL, verbose_name='utilisateur')),
            ],
            options={
                'verbose_name': 'profil élève',
                'verbose_name_plural': 'profils élèves',
            },
        ),
    ]
