# Generated by Django 6.0.4 on 2026-05-03 11:37

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
        ('exams', '0002_examfile_document_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamenBulletin',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('moyenne_generale', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='moyenne générale')),
                ('rang', models.PositiveIntegerField(default=0, verbose_name='rang')),
                ('effectif_total', models.PositiveIntegerField(default=0, verbose_name='effectif total')),
                ('decision_conseil', models.CharField(blank=True, default='', max_length=100, verbose_name='décision du conseil')),
                ('statut', models.CharField(choices=[('en_attente', "En attente d'approbation"), ('approuve', 'Approuvé'), ('rejete', 'Rejeté')], default='en_attente', max_length=20, verbose_name='statut')),
                ('appreciation_ia', models.TextField(blank=True, default='', verbose_name='synthèse IA')),
                ('file_pdf', models.FileField(blank=True, null=True, upload_to='bulletins_examens/%Y/%m/', verbose_name='fichier PDF')),
                ('verification_token', models.UUIDField(default=uuid.uuid4, unique=True, verbose_name='token de vérification')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approuve_at', models.DateTimeField(blank=True, null=True, verbose_name="date d'approbation")),
                ('approuve_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='examens_bulletins_approuves', to=settings.AUTH_USER_MODEL)),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examens_bulletins', to='core.classe')),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examens_bulletins', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "bulletin d'examen national",
                'verbose_name_plural': "bulletins d'examens nationaux",
                'ordering': ['rang', '-moyenne_generale'],
            },
        ),
        migrations.CreateModel(
            name='ExamenBulletinLigne',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('matiere', models.CharField(max_length=100, verbose_name='matière')),
                ('coefficient', models.DecimalField(decimal_places=2, default=1.0, max_digits=4, verbose_name='coefficient')),
                ('note_devoir', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='note devoir')),
                ('note_exam', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='note examen')),
                ('moyenne', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='moyenne')),
                ('rang', models.PositiveIntegerField(default=0, verbose_name='rang')),
                ('appreciation', models.TextField(blank=True, default='', verbose_name='appréciation')),
                ('bulletin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='exams.examenbulletin')),
            ],
            options={
                'verbose_name': 'ligne de bulletin examen',
                'verbose_name_plural': 'lignes de bulletin examens',
                'ordering': ['-moyenne'],
            },
        ),
        migrations.CreateModel(
            name='ExamenNational',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=200, verbose_name='nom')),
                ('type_examen', models.CharField(choices=[('bepc', 'BEPC'), ('cep', 'CEP'), ('bac_a1', 'Baccalauréat A1'), ('bac_a2', 'Baccalauréat A2'), ('bac_b', 'Baccalauréat B'), ('bac_c', 'Baccalauréat C'), ('bac_d', 'Baccalauréat D'), ('bac_e', 'Baccalauréat E'), ('bac_g1', 'Baccalauréat G1'), ('bac_g2', 'Baccalauréat G2'), ('bac_g3', 'Baccalauréat G3')], max_length=20, verbose_name="type d'examen")),
                ('annee_scolaire', models.CharField(default='2025-2026', max_length=20, verbose_name='année scolaire')),
                ('date_debut', models.DateField(verbose_name='date de début')),
                ('date_fin', models.DateField(verbose_name='date de fin')),
                ('horaires', models.JSONField(blank=True, default=dict, verbose_name='horaires')),
                ('coefficient_default', models.DecimalField(decimal_places=2, default=1.0, max_digits=4, verbose_name='coefficient par défaut')),
                ('coefficients_par_matiere', models.JSONField(blank=True, default=dict, verbose_name='coefficients par matière')),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon'), ('programme_publie', 'Programme publié'), ('en_cours', 'En cours'), ('termine', 'Terminé')], default='brouillon', max_length=30, verbose_name='statut')),
                ('instructions', models.TextField(blank=True, default='', verbose_name='instructions')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('classes', models.ManyToManyField(related_name='examens_nationaux', to='core.classe', verbose_name='classes concernées')),
                ('createur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examens_nationaux_crees', to=settings.AUTH_USER_MODEL)),
                ('matieres', models.ManyToManyField(related_name='examens_nationaux', to='core.matiere', verbose_name='matières concernées')),
            ],
            options={
                'verbose_name': 'examen national',
                'verbose_name_plural': 'examens nationaux',
                'ordering': ['-date_debut'],
            },
        ),
        migrations.AddField(
            model_name='examenbulletin',
            name='examen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bulletins', to='exams.examennational'),
        ),
        migrations.CreateModel(
            name='ExamenNationalMatiere',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('epreuve_file', models.FileField(upload_to='examens_nationaux/epreuves/%Y/%m/', verbose_name='épreuve')),
                ('corrige_type_file', models.FileField(upload_to='examens_nationaux/corriges/%Y/%m/', verbose_name='corrigé type')),
                ('epreuve_document_id', models.CharField(blank=True, editable=False, help_text='Identifiant unique pour le suivi IA', max_length=32, verbose_name='ID épreuve')),
                ('corrige_document_id', models.CharField(blank=True, editable=False, help_text='Identifiant unique pour le suivi IA', max_length=32, verbose_name='ID corrigé')),
                ('statut', models.CharField(choices=[('soumis', 'Soumis par le prof'), ('valide', "Validé par l'admin"), ('rejete', 'Rejeté')], default='soumis', max_length=20, verbose_name='statut')),
                ('commentaire_admin', models.TextField(blank=True, default='', verbose_name='commentaire admin')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('validated_at', models.DateTimeField(blank=True, null=True)),
                ('examen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examen_matieres', to='exams.examennational')),
                ('matiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examen_matieres', to='core.matiere')),
                ('soumis_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='examens_soumis', to=settings.AUTH_USER_MODEL)),
                ('valide_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='examens_valides', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "épreuve d'examen national",
                'verbose_name_plural': "épreuves d'examens nationaux",
                'unique_together': {('examen', 'matiere')},
            },
        ),
        migrations.CreateModel(
            name='ExamenComposition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('statut', models.CharField(choices=[('inscrit', 'Inscrit'), ('absent', 'Absent'), ('compose', 'A composé')], default='inscrit', max_length=20, verbose_name='statut')),
                ('moyenne_generale', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5, null=True, verbose_name='moyenne générale')),
                ('rang', models.PositiveIntegerField(default=0, verbose_name='rang')),
                ('resultat', models.CharField(blank=True, choices=[('admis', 'Admis'), ('ajourne', 'Ajourné'), ('refuse', 'Refusé')], default='admis', max_length=20, null=True, verbose_name='résultat')),
                ('details_notes', models.JSONField(blank=True, default=dict, verbose_name='détails des notes')),
                ('composed_at', models.DateTimeField(blank=True, null=True, verbose_name='date de composition')),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examen_compositions', to='core.classe')),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examen_compositions', to=settings.AUTH_USER_MODEL)),
                ('examen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compositions', to='exams.examennational')),
            ],
            options={
                'verbose_name': 'composition examen national',
                'verbose_name_plural': 'compositions examens nationaux',
                'ordering': ['rang', '-moyenne_generale'],
                'unique_together': {('examen', 'eleve')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='examenbulletin',
            unique_together={('examen', 'eleve')},
        ),
        migrations.CreateModel(
            name='ExamenReponseEleve',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('copie_file', models.FileField(blank=True, null=True, upload_to='examens_nationaux/copies/%Y/%m/', verbose_name="copie de l'élève")),
                ('copie_text', models.TextField(blank=True, default='', verbose_name='texte de la copie')),
                ('copie_document_id', models.CharField(blank=True, editable=False, help_text='Identifiant unique pour le suivi IA', max_length=32, verbose_name='ID copie')),
                ('statut', models.CharField(choices=[('soumis', 'Soumis'), ('en_cours_correction', 'En cours de correction IA'), ('corrige', 'Corrigé par IA'), ('approuve', 'Approuvé par admin'), ('rejete', 'Rejeté / à reprendre')], default='soumis', max_length=30, verbose_name='statut')),
                ('note_ia', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='note IA')),
                ('note_finale', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='note finale')),
                ('appreciation_ia', models.TextField(blank=True, default='', verbose_name='appréciation IA')),
                ('feedback_ia', models.JSONField(blank=True, default=dict, verbose_name='feedback détaillé IA')),
                ('soumis_par_admin', models.BooleanField(default=False, verbose_name='saisi par admin')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('corrige_at', models.DateTimeField(blank=True, null=True, verbose_name='date de correction')),
                ('approuve_at', models.DateTimeField(blank=True, null=True, verbose_name="date d'approbation")),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examen_reponses', to=settings.AUTH_USER_MODEL)),
                ('examen_matiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reponses', to='exams.examennationalmatiere')),
            ],
            options={
                'verbose_name': 'réponse élve examen',
                'verbose_name_plural': 'réponses élèves examens',
                'ordering': ['created_at'],
                'unique_together': {('examen_matiere', 'eleve')},
            },
        ),
    ]
