# Generated by Django 6.0.4 on 2026-05-09 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0003_examenbulletin_examenbulletinligne_examennational_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='rejection_comment',
            field=models.TextField(blank=True, verbose_name='raison du rejet'),
        ),
    ]
