# Generated by Django 5.2.13 on 2026-05-15 09:46

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_classe_niveau'),
        ('exams', '0004_exam_rejection_comment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamenBlanc',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titre', models.CharField(max_length=300, verbose_name='titre')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('type_examen_cible', models.CharField(blank=True, choices=[('bepc', 'BEPC'), ('cep', 'CEP'), ('bac_a1', 'Baccalauréat A1'), ('bac_a2', 'Baccalauréat A2'), ('bac_b', 'Baccalauréat B'), ('bac_c', 'Baccalauréat C'), ('bac_d', 'Baccalauréat D'), ('bac_e', 'Baccalauréat E'), ('bac_g1', 'Baccalauréat G1'), ('bac_g2', 'Baccalauréat G2'), ('bac_g3', 'Baccalauréat G3')], max_length=20, verbose_name='examen national simulé')),
                ('annee_scolaire', models.CharField(default='2025-2026', max_length=20, verbose_name='année scolaire')),
                ('date_examen', models.DateField(verbose_name="date de l'examen")),
                ('heure_debut', models.TimeField(verbose_name='heure de début')),
                ('heure_fin', models.TimeField(verbose_name='heure de fin')),
                ('lieu', models.CharField(blank=True, max_length=200, verbose_name='lieu')),
                ('duree_minutes', models.PositiveIntegerField(default=180, verbose_name='durée totale (minutes)')),
                ('camera_required', models.BooleanField(default=True, verbose_name='caméra obligatoire')),
                ('fullscreen_required', models.BooleanField(default=True, verbose_name='plein écran obligatoire')),
                ('anti_cheat_active', models.BooleanField(default=True, verbose_name='anti-triche actif')),
                ('acces_ressources_interdit', models.BooleanField(default=True, verbose_name='accès aux ressources interdit')),
                ('correction_ia_active', models.BooleanField(default=True, verbose_name='correction IA activée')),
                ('correction_humaine_requise', models.BooleanField(default=True, verbose_name='validation humaine requise')),
                ('seuil_admission', models.DecimalField(decimal_places=2, default=10.0, max_digits=4, verbose_name="seuil d'admission /20")),
                ('statut', models.CharField(choices=[('planifie', 'Planifié'), ('en_cours', 'En cours'), ('termine', 'Terminé'), ('annule', 'Annulé')], default='planifie', max_length=20, verbose_name='statut')),
                ('instructions', models.TextField(blank=True, verbose_name='instructions aux candidats')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examens_blancs', to='core.classe')),
                ('organise_par', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examens_blancs_crees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'examen blanc',
                'verbose_name_plural': 'examens blancs',
                'ordering': ['-date_examen'],
            },
        ),
        migrations.CreateModel(
            name='ExamenBlancMatiere',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('coefficient', models.DecimalField(decimal_places=2, default=1.0, max_digits=4, verbose_name='coefficient')),
                ('duree_minutes', models.PositiveIntegerField(default=60, verbose_name='durée (minutes)')),
                ('heure_debut', models.TimeField(verbose_name='heure de début')),
                ('heure_fin', models.TimeField(verbose_name='heure de fin')),
                ('epreuve_file', models.FileField(blank=True, null=True, upload_to='examens_blancs/epreuves/%Y/%m/', verbose_name='épreuve')),
                ('corrige_type_file', models.FileField(blank=True, null=True, upload_to='examens_blancs/corriges/%Y/%m/', verbose_name='corrigé type')),
                ('note_maximale', models.DecimalField(decimal_places=2, default=20.0, max_digits=5, verbose_name='note maximale')),
                ('examen_blanc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matieres', to='exams.examenblanc')),
                ('matiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examens_blancs', to='core.matiere')),
            ],
            options={
                'verbose_name': 'matière examen blanc',
                'verbose_name_plural': 'matières examens blancs',
                'unique_together': {('examen_blanc', 'matiere')},
            },
        ),
        migrations.CreateModel(
            name='ExamenBlancCopie',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('copie_file', models.FileField(blank=True, null=True, upload_to='examens_blancs/copies/%Y/%m/', verbose_name='copie')),
                ('copie_text', models.TextField(blank=True, verbose_name='texte de la copie')),
                ('temps_passe_minutes', models.PositiveIntegerField(default=0, verbose_name='temps passé (minutes)')),
                ('soumis_at', models.DateTimeField(blank=True, null=True, verbose_name='soumis le')),
                ('note_ia', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='note IA')),
                ('appreciation_ia', models.TextField(blank=True, verbose_name='appréciation IA')),
                ('feedback_ia', models.JSONField(blank=True, default=dict, verbose_name='feedback détaillé IA')),
                ('note_finale', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='note finale')),
                ('commentaire_prof', models.TextField(blank=True, verbose_name='commentaire professeur')),
                ('statut', models.CharField(choices=[('soumise', 'Soumise'), ('en_correction_ia', 'En correction IA'), ('corrigee_ia', 'Corrigée par IA'), ('validee', 'Validée par professeur'), ('contestee', 'Contestée')], default='soumise', max_length=25, verbose_name='statut')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('corrige_ia_at', models.DateTimeField(blank=True, null=True)),
                ('valide_at', models.DateTimeField(blank=True, null=True)),
                ('corrige_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='copies_corrigees_blancs', to=settings.AUTH_USER_MODEL)),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='copies_examens_blancs', to=settings.AUTH_USER_MODEL)),
                ('examen_matiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='copies', to='exams.examenblancmatiere')),
            ],
            options={
                'verbose_name': 'copie examen blanc',
                'verbose_name_plural': 'copies examens blancs',
                'unique_together': {('examen_matiere', 'eleve')},
            },
        ),
        migrations.CreateModel(
            name='RapportPerformanceExamenBlanc',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('moyenne_generale', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='moyenne générale /20')),
                ('rang_classe', models.PositiveIntegerField(default=0, verbose_name='rang dans la classe')),
                ('effectif_classe', models.PositiveIntegerField(default=0, verbose_name='effectif de la classe')),
                ('est_admis', models.BooleanField(default=False, verbose_name='admis (simulation)')),
                ('analyse_par_matiere', models.JSONField(blank=True, default=dict, verbose_name='analyse par matière')),
                ('types_erreurs', models.JSONField(blank=True, default=dict, verbose_name="types d'erreurs agrégés")),
                ('temps_total_minutes', models.PositiveIntegerField(default=0, verbose_name='temps total (minutes)')),
                ('temps_par_matiere', models.JSONField(blank=True, default=dict, verbose_name='temps par matière (minutes)')),
                ('synthese_ia', models.TextField(blank=True, verbose_name='synthèse IA')),
                ('recommandations', models.JSONField(blank=True, default=list, verbose_name='recommandations personnalisées')),
                ('progression_vs_precedent', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='progression vs examen précédent')),
                ('genere_at', models.DateTimeField(auto_now_add=True)),
                ('file_pdf', models.FileField(blank=True, null=True, upload_to='rapports_examens_blancs/%Y/%m/', verbose_name='rapport PDF')),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rapports_examens_blancs', to=settings.AUTH_USER_MODEL)),
                ('examen_blanc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rapports', to='exams.examenblanc')),
            ],
            options={
                'verbose_name': 'rapport de performance examen blanc',
                'verbose_name_plural': 'rapports de performance examens blancs',
                'ordering': ['-genere_at'],
                'unique_together': {('examen_blanc', 'eleve')},
            },
        ),
    ]
