# Generated by Django 6.0.4 — restructuration évaluations béninoises

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0005_examenblanc_examenblancmatiere_examenblanccopie_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # ── 1. Nettoyer les contraintes unique_together avant suppression ──────
        migrations.AlterUniqueTogether(
            name='examenblanccopie',
            unique_together=None,
        ),
        migrations.AlterUniqueTogether(
            name='examenblancmatiere',
            unique_together=None,
        ),
        migrations.AlterUniqueTogether(
            name='rapportperformanceexamenblanc',
            unique_together=None,
        ),

        # ── 2. Supprimer les modèles ExamenBlanc (non utilisés) ───────────────
        migrations.DeleteModel(name='ExamenBlancCopie'),
        migrations.DeleteModel(name='RapportPerformanceExamenBlanc'),
        migrations.DeleteModel(name='ExamenBlancMatiere'),
        migrations.DeleteModel(name='ExamenBlanc'),

        # ── 3. Ajouter le trimestre et mettre à jour le type sur Exam ─────────
        migrations.AddField(
            model_name='exam',
            name='trimestre',
            field=models.CharField(
                choices=[
                    ('T1', '1er Trimestre'),
                    ('T2', '2ème Trimestre'),
                    ('T3', '3ème Trimestre'),
                ],
                default='T1',
                help_text='Trimestre auquel appartient cette évaluation',
                max_length=2,
                verbose_name='trimestre',
            ),
        ),
        migrations.AlterField(
            model_name='exam',
            name='type_exam',
            field=models.CharField(
                choices=[
                    ('interrogation', 'Interrogation'),
                    ('devoir', 'Devoir Surveillé'),
                    ('composition', 'Composition Trimestrielle'),
                    ('examen', 'Examen'),
                    ('concours', 'Concours'),
                    ('eval_prof', 'Évaluation Professeur'),
                ],
                default='interrogation',
                max_length=20,
                verbose_name='type',
            ),
        ),

        # ── 4. Créer BulletinInterrogation ────────────────────────────────────
        migrations.CreateModel(
            name='BulletinInterrogation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('moyenne_classe', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='moyenne de la classe')),
                ('note_plus_haute', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='note la plus haute')),
                ('note_plus_basse', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='note la plus basse')),
                ('effectif_total', models.PositiveSmallIntegerField(default=0, verbose_name='effectif total')),
                ('nombre_absents', models.PositiveSmallIntegerField(default=0, verbose_name="nombre d'absents")),
                ('statut', models.CharField(
                    choices=[('brouillon', 'Brouillon'), ('publie', 'Publié')],
                    default='brouillon', max_length=20, verbose_name='statut'
                )),
                ('file_pdf', models.FileField(blank=True, null=True, upload_to='bulletins_interrogations/%Y/%m/', verbose_name='fichier PDF')),
                ('verification_token', models.UUIDField(default=uuid.uuid4, unique=True, verbose_name='token de vérification')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('publie_at', models.DateTimeField(blank=True, null=True, verbose_name='publié le')),
                ('classe', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='bulletins_interrogation', to='core.classe'
                )),
                ('exam', models.OneToOneField(
                    limit_choices_to={'type_exam': 'interrogation'},
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='bulletin_interrogation', to='exams.exam'
                )),
                ('publie_par', models.ForeignKey(
                    blank=True, null=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    related_name='bulletins_interro_publies',
                    to=settings.AUTH_USER_MODEL
                )),
            ],
            options={
                'verbose_name': "relevé d'interrogation",
                'verbose_name_plural': "relevés d'interrogation",
            },
        ),

        # ── 5. Créer NoteInterrogation ────────────────────────────────────────
        migrations.CreateModel(
            name='NoteInterrogation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('note', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='note obtenue')),
                ('note_sur', models.DecimalField(decimal_places=2, default=20.0, max_digits=5, verbose_name='note maximale')),
                ('appreciation', models.TextField(blank=True, default='', verbose_name='appréciation du prof')),
                ('absent', models.BooleanField(default=False, verbose_name='absent')),
                ('corrige_at', models.DateTimeField(blank=True, null=True, verbose_name='corrigé le')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('corrige_par', models.ForeignKey(
                    blank=True, null=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    related_name='interros_corrigees',
                    to=settings.AUTH_USER_MODEL
                )),
                ('eleve', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='notes_interrogation',
                    to=settings.AUTH_USER_MODEL
                )),
                ('exam', models.ForeignKey(
                    limit_choices_to={'type_exam': 'interrogation'},
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='notes_interrogation', to='exams.exam'
                )),
            ],
            options={
                'verbose_name': "note d'interrogation",
                'verbose_name_plural': "notes d'interrogation",
                'ordering': ['exam__date_debut', 'eleve'],
                'unique_together': {('exam', 'eleve')},
            },
        ),
    ]
