# Generated by Django 6.0.4 on 2026-05-20 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0006_restructuration_evaluations_beninois'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='telephone_prof_beneficiaire',
            field=models.CharField(blank=True, help_text='Numéro MTN/Moov du professeur — recevra 50 % du paiement correction élève', max_length=20, verbose_name='téléphone prof bénéficiaire (Mobile Money)'),
        ),
    ]
