# Generated by Django 6.0.4 on 2026-05-11 07:09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('lien_parente', models.CharField(choices=[('pere', 'Père'), ('mere', 'Mère'), ('tuteur', 'Tuteur légal'), ('oncle', 'Oncle'), ('tante', 'Tante'), ('grand_parent', 'Grand-parent'), ('autre', 'Autre')], default='pere', max_length=20, verbose_name='lien de parenté')),
                ('profession', models.CharField(blank=True, max_length=100, verbose_name='profession')),
                ('lieu_travail', models.CharField(blank=True, max_length=200, verbose_name='lieu de travail')),
                ('telephone_2', models.CharField(blank=True, max_length=20, verbose_name='téléphone 2')),
                ('email_2', models.EmailField(blank=True, max_length=254, verbose_name='email 2')),
                ('adresse', models.TextField(blank=True, verbose_name='adresse')),
                ('is_actif', models.BooleanField(default=True, verbose_name='compte actif')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(limit_choices_to={'role': 'parent'}, on_delete=django.db.models.deletion.CASCADE, related_name='profil_parent', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Parent',
                'verbose_name_plural': 'Parents',
            },
        ),
        migrations.CreateModel(
            name='NotificationParent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type_notification', models.CharField(choices=[('absence', 'Absence enregistrée'), ('retard', 'Retard signalé'), ('note', 'Nouvelle note'), ('bulletin', 'Bulletin disponible'), ('paiement', 'Paiement requis'), ('evenement', 'Événement scolaire'), ('discipline', 'Incident disciplinaire'), ('generale', 'Information générale')], max_length=20, verbose_name='type')),
                ('titre', models.CharField(max_length=200, verbose_name='titre')),
                ('contenu', models.TextField(verbose_name='contenu')),
                ('is_lue', models.BooleanField(default=False, verbose_name='lue')),
                ('date_notification', models.DateTimeField(auto_now_add=True)),
                ('eleve', models.ForeignKey(limit_choices_to={'role': 'eleve'}, on_delete=django.db.models.deletion.CASCADE, related_name='notifications_parent', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='parents.parent')),
            ],
            options={
                'verbose_name': 'Notification parent',
                'verbose_name_plural': 'Notifications parents',
                'ordering': ['-date_notification'],
            },
        ),
        migrations.CreateModel(
            name='Enfant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_principal', models.BooleanField(default=False, verbose_name='tuteur principal')),
                ('autorisation_sortie', models.BooleanField(default=True, verbose_name='autorisation de sortie')),
                ('autorisation_medical', models.BooleanField(default=True, verbose_name='autorisation médicale')),
                ('eleve', models.ForeignKey(limit_choices_to={'role': 'eleve'}, on_delete=django.db.models.deletion.CASCADE, related_name='parents', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enfants', to='parents.parent')),
            ],
            options={
                'verbose_name': 'Enfant',
                'verbose_name_plural': 'Enfants',
                'unique_together': {('parent', 'eleve')},
            },
        ),
    ]
