# Generated by Django 6.0.4 on 2026-05-02 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compositions', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentsubmissionfile',
            name='document_id',
            field=models.CharField(blank=True, editable=False, help_text='Identifiant unique pour le suivi IA', max_length=32, verbose_name='ID document'),
        ),
    ]
