# Generated by Django 6.0.4 on 2026-05-11 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compositions', '0003_studentsubmissionfile_document_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anticheatlog',
            name='type_event',
            field=models.CharField(choices=[('tab_change', "Changement d'onglet"), ('fullscreen_exit', 'Sortie plein écran'), ('camera_off', 'Caméra désactivée'), ('multiple_faces', 'Plusieurs visages détectés'), ('copy_paste', 'Copier/Coller'), ('right_click', 'Clic droit'), ('suspicious_movement', 'Mouvement suspect'), ('devtools_attempt', 'Tentative DevTools'), ('print_attempt', 'Tentative impression'), ('text_selection', 'Sélection de texte')], max_length=30, verbose_name="type d'événement"),
        ),
    ]
