# Generated by Django 5.2.13 on 2026-05-14 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compositions', '0004_alter_anticheatlog_type_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compositionsession',
            name='statut',
            field=models.CharField(choices=[('en_attente', 'En attente'), ('en_cours', 'En cours'), ('soumis', 'Soumis'), ('en_correction', 'En correction'), ('corrige', 'Corrigé'), ('exclu', 'Exclu (triche)')], db_index=True, default='en_attente', max_length=20, verbose_name='statut'),
        ),
    ]
