# Generated by Django 5.2.13 on 2026-05-15 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compositions', '0005_alter_compositionsession_statut'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultat',
            name='apercu_correction',
            field=models.JSONField(blank=True, help_text='Données partielles montrées avant paiement', null=True, verbose_name='aperçu correction (paywall)'),
        ),
        migrations.AddField(
            model_name='resultat',
            name='correction_complete',
            field=models.BooleanField(default=True, help_text="False = paywall actif, seul l'aperçu est affiché", verbose_name='correction complète visible'),
        ),
        migrations.AlterField(
            model_name='compositionsession',
            name='statut',
            field=models.CharField(choices=[('en_attente', 'En attente'), ('en_cours', 'En cours'), ('soumis', 'Soumis'), ('en_correction', 'En correction'), ('corrige', 'Corrigé'), ('bloque', 'Correction verrouillée (paywall)'), ('exclu', 'Exclu (triche)')], db_index=True, default='en_attente', max_length=20, verbose_name='statut'),
        ),
    ]
