# Generated by Django 6.0.4 on 2026-05-11 07:09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0003_alter_classe_niveau'),
        ('schools', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmploiDuTemps',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type_cible', models.CharField(choices=[('classe', 'Classe'), ('professeur', 'Professeur'), ('salle', 'Salle'), ('etablissement', 'Établissement')], max_length=20, verbose_name='type de cible')),
                ('salle', models.CharField(blank=True, max_length=50, verbose_name='salle')),
                ('annee_scolaire', models.CharField(default='2024-2025', max_length=9, verbose_name='année scolaire')),
                ('semestre', models.CharField(default='Semestre 1', max_length=20, verbose_name='semestre')),
                ('nom', models.CharField(max_length=200, verbose_name="nom de l'emploi du temps")),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('is_actif', models.BooleanField(default=True, verbose_name='actif')),
                ('is_public', models.BooleanField(default=False, verbose_name='public')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('classe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='emplois_du_temps', to='schools.classe')),
                ('etablissement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emplois_du_temps', to='schools.etablissement')),
                ('professeur', models.ForeignKey(blank=True, limit_choices_to={'role': 'professeur'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emplois_du_temps', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Emploi du temps',
                'verbose_name_plural': 'Emplois du temps',
                'ordering': ['annee_scolaire', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='CreneauHoraire',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('jour', models.CharField(choices=[('lundi', 'Lundi'), ('mardi', 'Mardi'), ('mercredi', 'Mercredi'), ('jeudi', 'Jeudi'), ('vendredi', 'Vendredi'), ('samedi', 'Samedi'), ('dimanche', 'Dimanche')], max_length=20, verbose_name='jour')),
                ('heure_debut', models.TimeField(verbose_name='heure de début')),
                ('heure_fin', models.TimeField(verbose_name='heure de fin')),
                ('salle', models.CharField(blank=True, max_length=50, verbose_name='salle')),
                ('couleur', models.CharField(default='#3b82f6', max_length=7, verbose_name='couleur')),
                ('note', models.TextField(blank=True, verbose_name='note')),
                ('is_actif', models.BooleanField(default=True, verbose_name='actif')),
                ('classe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='creneaux', to='schools.classe')),
                ('matiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creneaux', to='core.matiere')),
                ('professeur', models.ForeignKey(blank=True, limit_choices_to={'role': 'professeur'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='creneaux', to=settings.AUTH_USER_MODEL)),
                ('emploi_du_temps', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creneaux', to='schedule.emploidutemps')),
            ],
            options={
                'verbose_name': 'Créneau horaire',
                'verbose_name_plural': 'Créneaux horaires',
                'ordering': ['jour', 'heure_debut'],
            },
        ),
        migrations.CreateModel(
            name='EvenementScolaire',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titre', models.CharField(max_length=200, verbose_name='titre')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('type_evenement', models.CharField(choices=[('examen', 'Examen'), ('reunion', 'Réunion'), ('activite', 'Activité'), ('conferences', 'Conférences'), ('sortie', 'Sortie'), ('fete', 'Fête'), ('autre', 'Autre')], max_length=20, verbose_name="type d'événement")),
                ('date_debut', models.DateTimeField(verbose_name='date et heure de début')),
                ('date_fin', models.DateTimeField(verbose_name='date et heure de fin')),
                ('duree', models.PositiveIntegerField(blank=True, null=True, verbose_name='durée (minutes)')),
                ('lieu', models.CharField(blank=True, max_length=200, verbose_name='lieu')),
                ('salle', models.CharField(blank=True, max_length=50, verbose_name='salle')),
                ('priorite', models.CharField(choices=[('basse', 'Basse'), ('normale', 'Normale'), ('haute', 'Haute'), ('urgente', 'Urgente')], default='normale', max_length=20, verbose_name='priorité')),
                ('rappel_avant', models.PositiveIntegerField(default=24, verbose_name='rappel (heures avant)')),
                ('is_annule', models.BooleanField(default=False, verbose_name='annulé')),
                ('motif_annulation', models.TextField(blank=True, verbose_name="motif d'annulation")),
                ('couleur', models.CharField(default='#10b981', max_length=7, verbose_name='couleur')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('classes_concernees', models.ManyToManyField(blank=True, related_name='evenements', to='schools.classe')),
                ('etablissement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evenements', to='schools.etablissement')),
                ('organisateur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evenements_organises', to=settings.AUTH_USER_MODEL)),
                ('participants', models.ManyToManyField(blank=True, related_name='evenements_participes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Événement scolaire',
                'verbose_name_plural': 'Événements scolaires',
                'ordering': ['date_debut'],
            },
        ),
        migrations.CreateModel(
            name='Salle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100, verbose_name='nom de la salle')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='code')),
                ('type_salle', models.CharField(choices=[('classe', 'Salle de classe'), ('laboratoire', 'Laboratoire'), ('info', 'Salle informatique'), ('sport', 'Salle de sport'), ('reunion', 'Salle de réunion'), ('bibliotheque', 'Bibliothèque'), ('cantine', 'Cantine'), ('autre', 'Autre')], max_length=20, verbose_name='type de salle')),
                ('capacite', models.PositiveIntegerField(default=30, verbose_name='capacité')),
                ('superficie', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='superficie (m²)')),
                ('equipements', models.TextField(blank=True, help_text='Liste des équipements séparés par des virgules', verbose_name='équipements')),
                ('etage', models.CharField(blank=True, max_length=20, verbose_name='étage')),
                ('batiment', models.CharField(blank=True, max_length=50, verbose_name='bâtiment')),
                ('is_disponible', models.BooleanField(default=True, verbose_name='disponible')),
                ('is_accessible', models.BooleanField(default=False, verbose_name='accessible PMR')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('campus', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='salles', to='schools.campus')),
                ('etablissement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salles', to='schools.etablissement')),
            ],
            options={
                'verbose_name': 'Salle',
                'verbose_name_plural': 'Salles',
                'ordering': ['batiment', 'etage', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='DisponibiliteProfesseur',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('jour', models.CharField(choices=[('lundi', 'Lundi'), ('mardi', 'Mardi'), ('mercredi', 'Mercredi'), ('jeudi', 'Jeudi'), ('vendredi', 'Vendredi'), ('samedi', 'Samedi'), ('dimanche', 'Dimanche')], max_length=20, verbose_name='jour')),
                ('heure_debut_matin', models.TimeField(blank=True, null=True, verbose_name='heure début matin')),
                ('heure_fin_matin', models.TimeField(blank=True, null=True, verbose_name='heure fin matin')),
                ('heure_debut_apresmidi', models.TimeField(blank=True, null=True, verbose_name='heure début après-midi')),
                ('heure_fin_apresmidi', models.TimeField(blank=True, null=True, verbose_name='heure fin après-midi')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('is_actif', models.BooleanField(default=True, verbose_name='actif')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('professeur', models.ForeignKey(limit_choices_to={'role': 'professeur'}, on_delete=django.db.models.deletion.CASCADE, related_name='disponibilites', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Disponibilité professeur',
                'verbose_name_plural': 'Disponibilités professeurs',
                'ordering': ['professeur', 'jour'],
                'unique_together': {('professeur', 'jour')},
            },
        ),
    ]
