# Generated by Django 6.0.4 on 2026-05-11 07:09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type_conversation', models.CharField(choices=[('prive', 'Privé'), ('groupe', 'Groupe'), ('classe', 'Classe'), ('admin', 'Administration')], default='prive', max_length=20, verbose_name='type')),
                ('titre', models.CharField(blank=True, max_length=200, verbose_name='titre')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('image', models.ImageField(blank=True, null=True, upload_to='conversations/', verbose_name='image')),
                ('nombre_messages', models.PositiveIntegerField(default=0, verbose_name='nombre de messages')),
                ('is_actif', models.BooleanField(default=True, verbose_name='actif')),
                ('is_archive', models.BooleanField(default=False, verbose_name='archivé')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='date de création')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='date de modification')),
                ('administrateurs', models.ManyToManyField(blank=True, related_name='conversations_administrees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Conversation',
                'verbose_name_plural': 'Conversations',
                'ordering': ['-date_modification'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type_message', models.CharField(choices=[('texte', 'Texte'), ('image', 'Image'), ('fichier', 'Fichier'), ('audio', 'Audio'), ('video', 'Vidéo'), ('lien', 'Lien'), ('localisation', 'Localisation')], default='texte', max_length=20, verbose_name='type')),
                ('contenu', models.TextField(verbose_name='contenu')),
                ('fichier', models.FileField(blank=True, null=True, upload_to='messages/fichiers/', verbose_name='fichier')),
                ('miniature', models.ImageField(blank=True, null=True, upload_to='messages/miniatures/', verbose_name='miniature')),
                ('nom_fichier', models.CharField(blank=True, max_length=255, verbose_name='nom du fichier')),
                ('taille_fichier', models.PositiveIntegerField(blank=True, null=True, verbose_name='taille du fichier (octets)')),
                ('is_supprime', models.BooleanField(default=False, verbose_name='supprimé')),
                ('is_modifie', models.BooleanField(default=False, verbose_name='modifié')),
                ('reactions', models.JSONField(blank=True, default=dict, null=True, verbose_name='réactions')),
                ('date_envoi', models.DateTimeField(auto_now_add=True, verbose_name="date d'envoi")),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='date de modification')),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='messaging.conversation')),
                ('expediteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages_envoyes', to=settings.AUTH_USER_MODEL)),
                ('message_parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reponses', to='messaging.message')),
                ('utilisateurs_lus', models.ManyToManyField(blank=True, related_name='messages_lus', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Message',
                'verbose_name_plural': 'Messages',
                'ordering': ['date_envoi'],
            },
        ),
        migrations.AddField(
            model_name='conversation',
            name='dernier_message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversation_dernier', to='messaging.message'),
        ),
        migrations.CreateModel(
            name='NotificationMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type_notification', models.CharField(choices=[('nouveau_message', 'Nouveau message'), ('mention', 'Mention'), ('reaction', 'Réaction'), ('ajout_groupe', 'Ajout au groupe'), ('invitation', 'Invitation')], max_length=20, verbose_name='type')),
                ('titre', models.CharField(max_length=200, verbose_name='titre')),
                ('contenu', models.TextField(verbose_name='contenu')),
                ('is_lue', models.BooleanField(default=False, verbose_name='lue')),
                ('is_cliquee', models.BooleanField(default=False, verbose_name='cliquée')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='date de création')),
                ('date_lecture', models.DateTimeField(blank=True, null=True, verbose_name='date de lecture')),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='messaging.conversation')),
                ('message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='messaging.message')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification de message',
                'verbose_name_plural': 'Notifications de messages',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='ParticipantConversation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_admin', models.BooleanField(default=False, verbose_name='administrateur')),
                ('is_muet', models.BooleanField(default=False, verbose_name='muet')),
                ('notifications_actives', models.BooleanField(default=True, verbose_name='notifications actives')),
                ('nombre_non_lus', models.PositiveIntegerField(default=0, verbose_name='messages non lus')),
                ('date_rejoint', models.DateTimeField(auto_now_add=True, verbose_name='date de participation')),
                ('date_dernier_message_lu', models.DateTimeField(blank=True, null=True, verbose_name='dernier message lu')),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='messaging.conversation')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Participant',
                'verbose_name_plural': 'Participants',
                'unique_together': {('conversation', 'utilisateur')},
            },
        ),
        migrations.AddField(
            model_name='conversation',
            name='participants',
            field=models.ManyToManyField(related_name='conversations', through='messaging.ParticipantConversation', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='InvitationConversation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('message', models.TextField(blank=True, verbose_name="message d'invitation")),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('acceptee', 'Acceptée'), ('refusee', 'Refusée'), ('expiree', 'Expirée')], default='en_attente', max_length=20, verbose_name='statut')),
                ('date_invitation', models.DateTimeField(auto_now_add=True, verbose_name="date d'invitation")),
                ('date_reponse', models.DateTimeField(blank=True, null=True, verbose_name='date de réponse')),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='messaging.conversation')),
                ('invite_par', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations_envoyees', to=settings.AUTH_USER_MODEL)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations_recues', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Invitation',
                'verbose_name_plural': 'Invitations',
                'unique_together': {('conversation', 'utilisateur')},
            },
        ),
        migrations.CreateModel(
            name='MessageFavori',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('note', models.TextField(blank=True, verbose_name='note personnelle')),
                ('date_ajout', models.DateTimeField(auto_now_add=True, verbose_name="date d'ajout")),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favoris', to='messaging.message')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages_favoris', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Message favori',
                'verbose_name_plural': 'Messages favoris',
                'unique_together': {('utilisateur', 'message')},
            },
        ),
    ]
