# Generated by Django 5.2.13 on 2026-05-14 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='is_supprime',
            field=models.BooleanField(db_index=True, default=False, verbose_name='supprimé'),
        ),
    ]
