# Generated by Django 6.0.4 on 2026-05-01 18:26

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Devoir',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titre', models.CharField(max_length=300, verbose_name='titre')),
                ('description', models.TextField(blank=True, default='', verbose_name='description')),
                ('annee_scolaire', models.CharField(default='2025-2026', max_length=20, verbose_name='année scolaire')),
                ('date_debut', models.DateField(verbose_name='date de début')),
                ('date_fin', models.DateField(verbose_name='date de fin')),
                ('horaires', models.JSONField(blank=True, default=dict, verbose_name='horaires')),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon'), ('programme_publie', 'Programme publié'), ('en_cours', 'En cours'), ('termine', 'Terminé')], default='brouillon', max_length=30, verbose_name='statut')),
                ('instructions', models.TextField(blank=True, default='', verbose_name='instructions')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('classes', models.ManyToManyField(related_name='devoirs', to='core.classe', verbose_name='classes concernées')),
                ('createur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devoirs_crees', to=settings.AUTH_USER_MODEL)),
                ('matieres', models.ManyToManyField(related_name='devoirs', to='core.matiere', verbose_name='matières concernées')),
            ],
            options={
                'verbose_name': 'devoir national',
                'verbose_name_plural': 'devoirs nationaux',
                'ordering': ['-date_debut'],
            },
        ),
        migrations.CreateModel(
            name='Certificat',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type_certificat', models.CharField(choices=[('admission', 'Admission'), ('excellence', 'Excellence'), ('participation', 'Participation'), ('fin_annee', "Fin d'année")], default='admission', max_length=20, verbose_name='type')),
                ('moyenne_obtenue', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='moyenne')),
                ('mention', models.TextField(blank=True, default='', verbose_name='mention')),
                ('numero_certificat', models.CharField(blank=True, max_length=30, unique=True, verbose_name='numéro')),
                ('date_delivrance', models.DateField(auto_now_add=True, verbose_name='date de délivrance')),
                ('file_pdf', models.FileField(blank=True, null=True, upload_to='certificats/%Y/%m/', verbose_name='fichier PDF')),
                ('verification_token', models.UUIDField(default=uuid.uuid4, unique=True, verbose_name='token de vérification')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificats', to=settings.AUTH_USER_MODEL)),
                ('devoir', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certificats', to='devoirs.devoir')),
            ],
            options={
                'verbose_name': 'certificat',
                'verbose_name_plural': 'certificats',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DevoirComposition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('statut', models.CharField(choices=[('inscrit', 'Inscrit'), ('absent', 'Absent'), ('compose', 'A composé')], default='inscrit', max_length=20, verbose_name='statut')),
                ('moyenne_generale', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5, null=True, verbose_name='moyenne générale')),
                ('rang', models.PositiveIntegerField(default=0, verbose_name='rang')),
                ('resultat', models.CharField(blank=True, choices=[('admis', 'Admis'), ('ajourne', 'Ajourné'), ('refuse', 'Refusé')], default='admis', max_length=20, null=True, verbose_name='résultat')),
                ('details_notes', models.JSONField(blank=True, default=dict, verbose_name='détails des notes')),
                ('composed_at', models.DateTimeField(blank=True, null=True, verbose_name='date de composition')),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devoir_compositions', to='core.classe')),
                ('devoir', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compositions', to='devoirs.devoir')),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devoir_compositions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'composition devoir',
                'verbose_name_plural': 'compositions devoirs',
                'ordering': ['rang', '-moyenne_generale'],
                'unique_together': {('devoir', 'eleve')},
            },
        ),
        migrations.CreateModel(
            name='DevoirMatiere',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('epreuve_file', models.FileField(upload_to='devoirs/epreuves/%Y/%m/', verbose_name='épreuve')),
                ('corrige_type_file', models.FileField(upload_to='devoirs/corriges/%Y/%m/', verbose_name='corrigé type')),
                ('statut', models.CharField(choices=[('soumis', 'Soumis par le prof'), ('valide', "Validé par l'admin"), ('rejete', 'Rejeté')], default='soumis', max_length=20, verbose_name='statut')),
                ('commentaire_admin', models.TextField(blank=True, default='', verbose_name='commentaire admin')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('validated_at', models.DateTimeField(blank=True, null=True)),
                ('devoir', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devoir_matieres', to='devoirs.devoir')),
                ('matiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devoir_matieres', to='core.matiere')),
                ('soumis_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devoirs_soumis', to=settings.AUTH_USER_MODEL)),
                ('valide_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devoirs_valides', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'épreuve de devoir',
                'verbose_name_plural': 'épreuves de devoir',
                'unique_together': {('devoir', 'matiere')},
            },
        ),
    ]
