# Generated by Django 6.0.4 on 2026-05-01 20:56

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
        ('devoirs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='devoir',
            name='coefficient_default',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=4, verbose_name='coefficient par défaut'),
        ),
        migrations.AddField(
            model_name='devoir',
            name='coefficients_par_matiere',
            field=models.JSONField(blank=True, default=dict, verbose_name='coefficients par matière'),
        ),
        migrations.CreateModel(
            name='BulletinDevoir',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('moyenne_generale', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='moyenne générale')),
                ('rang', models.PositiveIntegerField(default=0, verbose_name='rang')),
                ('effectif_total', models.PositiveIntegerField(default=0, verbose_name='effectif total')),
                ('decision_conseil', models.CharField(blank=True, default='', max_length=100, verbose_name='décision du conseil')),
                ('statut', models.CharField(choices=[('en_attente', "En attente d'approbation"), ('approuve', 'Approuvé'), ('rejete', 'Rejeté')], default='en_attente', max_length=20, verbose_name='statut')),
                ('appreciation_ia', models.TextField(blank=True, default='', verbose_name='synthèse IA')),
                ('file_pdf', models.FileField(blank=True, null=True, upload_to='bulletins_devoirs/%Y/%m/', verbose_name='fichier PDF')),
                ('verification_token', models.UUIDField(default=uuid.uuid4, unique=True, verbose_name='token de vérification')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approuve_at', models.DateTimeField(blank=True, null=True, verbose_name="date d'approbation")),
                ('approuve_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bulletins_approuves', to=settings.AUTH_USER_MODEL)),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bulletins_devoir', to='core.classe')),
                ('devoir', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bulletins', to='devoirs.devoir')),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bulletins_devoir', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'bulletin de devoir',
                'verbose_name_plural': 'bulletins de devoirs',
                'ordering': ['rang', '-moyenne_generale'],
                'unique_together': {('devoir', 'eleve')},
            },
        ),
        migrations.CreateModel(
            name='BulletinDevoirLigne',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('matiere', models.CharField(max_length=100, verbose_name='matière')),
                ('coefficient', models.DecimalField(decimal_places=2, default=1.0, max_digits=4, verbose_name='coefficient')),
                ('note_devoir', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='note devoir')),
                ('note_exam', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='note examen')),
                ('moyenne', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='moyenne')),
                ('rang', models.PositiveIntegerField(default=0, verbose_name='rang')),
                ('appreciation', models.TextField(blank=True, default='', verbose_name='appréciation')),
                ('bulletin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='devoirs.bulletindevoir')),
            ],
            options={
                'verbose_name': 'ligne de bulletin',
                'verbose_name_plural': 'lignes de bulletin',
                'ordering': ['-moyenne'],
            },
        ),
        migrations.CreateModel(
            name='DevoirReponseEleve',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('copie_file', models.FileField(blank=True, null=True, upload_to='devoirs/copies/%Y/%m/', verbose_name="copie de l'élève")),
                ('copie_text', models.TextField(blank=True, default='', verbose_name='texte de la copie')),
                ('statut', models.CharField(choices=[('soumis', 'Soumis'), ('en_cours_correction', 'En cours de correction IA'), ('corrige', 'Corrigé par IA'), ('approuve', 'Approuvé par admin'), ('rejete', 'Rejeté / à reprendre')], default='soumis', max_length=30, verbose_name='statut')),
                ('note_ia', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='note IA')),
                ('note_finale', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='note finale')),
                ('appreciation_ia', models.TextField(blank=True, default='', verbose_name='appréciation IA')),
                ('feedback_ia', models.JSONField(blank=True, default=dict, verbose_name='feedback détaillé IA')),
                ('soumis_par_admin', models.BooleanField(default=False, verbose_name='saisi par admin')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('corrige_at', models.DateTimeField(blank=True, null=True, verbose_name='date de correction')),
                ('approuve_at', models.DateTimeField(blank=True, null=True, verbose_name="date d'approbation")),
                ('devoir_matiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reponses', to='devoirs.devoirmatiere')),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devoir_reponses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'réponse élève',
                'verbose_name_plural': 'réponses élèves',
                'ordering': ['created_at'],
                'unique_together': {('devoir_matiere', 'eleve')},
            },
        ),
    ]
