# Generated by Django 6.0.4 on 2026-05-02 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devoirs', '0002_devoir_coefficient_default_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='devoirmatiere',
            name='corrige_document_id',
            field=models.CharField(blank=True, editable=False, help_text='Identifiant unique pour le suivi IA', max_length=32, verbose_name='ID corrigé'),
        ),
        migrations.AddField(
            model_name='devoirmatiere',
            name='epreuve_document_id',
            field=models.CharField(blank=True, editable=False, help_text='Identifiant unique pour le suivi IA', max_length=32, verbose_name='ID épreuve'),
        ),
        migrations.AddField(
            model_name='devoirreponseeleve',
            name='copie_document_id',
            field=models.CharField(blank=True, editable=False, help_text='Identifiant unique pour le suivi IA', max_length=32, verbose_name='ID copie'),
        ),
    ]
