# Generated by Django 6.0.4 on 2026-05-04 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devoirs', '0003_devoirmatiere_corrige_document_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bulletindevoir',
            name='prof_lu',
            field=models.BooleanField(default=False, help_text='Indique si le professeur a pris connaissance du bulletin', verbose_name='lu par le professeur'),
        ),
    ]
