# Generated by Django 6.0.4 on 2026-05-09 20:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_classe_niveau'),
        ('devoirs', '0004_bulletindevoir_prof_lu'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificat',
            name='eleve',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificats_devoirs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='devoir',
            name='matieres',
            field=models.ManyToManyField(related_name='devoirs_nationaux', to='core.matiere', verbose_name='matières concernées'),
        ),
    ]
