# Generated by Django 6.0.4 on 2026-05-16 17:01

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devoirs', '0005_alter_certificat_eleve_alter_devoir_matieres'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bulletindevoir',
            options={'ordering': ['rang', '-moyenne_generale'], 'verbose_name': "bulletin d'évaluation", 'verbose_name_plural': "bulletins d'évaluation"},
        ),
        migrations.AlterModelOptions(
            name='bulletindevoirligne',
            options={'ordering': ['matiere'], 'verbose_name': 'ligne de bulletin', 'verbose_name_plural': 'lignes de bulletin'},
        ),
        migrations.AlterModelOptions(
            name='devoir',
            options={'ordering': ['-date_debut'], 'verbose_name': "calendrier d'évaluation", 'verbose_name_plural': "calendriers d'évaluation"},
        ),
        migrations.AlterModelOptions(
            name='devoirmatiere',
            options={'ordering': ['numero_ordre', 'date_epreuve', 'heure_debut'], 'verbose_name': 'programme de matière', 'verbose_name_plural': 'programmes par matière'},
        ),
        migrations.RemoveField(
            model_name='bulletindevoirligne',
            name='note_exam',
        ),
        migrations.RemoveField(
            model_name='devoir',
            name='coefficients_par_matiere',
        ),
        migrations.RemoveField(
            model_name='devoir',
            name='horaires',
        ),
        migrations.AddField(
            model_name='bulletindevoir',
            name='absences_justifiees',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='absences justifiées (h)'),
        ),
        migrations.AddField(
            model_name='bulletindevoir',
            name='absences_non_justifiees',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='absences non justifiées (h)'),
        ),
        migrations.AddField(
            model_name='bulletindevoir',
            name='observation_prof_principal',
            field=models.TextField(blank=True, default='', verbose_name='observation du professeur principal'),
        ),
        migrations.AddField(
            model_name='bulletindevoir',
            name='retards',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='retards'),
        ),
        migrations.AddField(
            model_name='bulletindevoirligne',
            name='moyenne_classe',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='moy. de la classe'),
        ),
        migrations.AddField(
            model_name='bulletindevoirligne',
            name='note_composition',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Note de la composition trimestrielle (examen de fin de trimestre)', max_digits=5, null=True, verbose_name='note composition'),
        ),
        migrations.AddField(
            model_name='bulletindevoirligne',
            name='note_interro_moyenne',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Moyenne des interrogations du trimestre pour cette matière', max_digits=5, null=True, verbose_name='moy. interrogations'),
        ),
        migrations.AddField(
            model_name='bulletindevoirligne',
            name='note_moy_coeff',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Utilisé pour le calcul de la moyenne générale pondérée', max_digits=6, verbose_name='moy × coeff'),
        ),
        migrations.AddField(
            model_name='devoir',
            name='trimestre',
            field=models.CharField(choices=[('T1', '1er Trimestre'), ('T2', '2ème Trimestre'), ('T3', '3ème Trimestre')], default='T1', max_length=2, verbose_name='trimestre'),
        ),
        migrations.AddField(
            model_name='devoir',
            name='type_evaluation',
            field=models.CharField(choices=[('devoir_surveille', 'Devoir Surveillé'), ('composition', 'Composition Trimestrielle')], default='devoir_surveille', max_length=20, verbose_name="type d'évaluation"),
        ),
        migrations.AddField(
            model_name='devoirmatiere',
            name='coefficient',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=4, verbose_name='coefficient'),
        ),
        migrations.AddField(
            model_name='devoirmatiere',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='créé le'),
        ),
        migrations.AddField(
            model_name='devoirmatiere',
            name='date_epreuve',
            field=models.DateField(blank=True, null=True, verbose_name="date de l'épreuve"),
        ),
        migrations.AddField(
            model_name='devoirmatiere',
            name='heure_debut',
            field=models.TimeField(blank=True, null=True, verbose_name='heure de début'),
        ),
        migrations.AddField(
            model_name='devoirmatiere',
            name='heure_fin',
            field=models.TimeField(blank=True, null=True, verbose_name='heure de fin'),
        ),
        migrations.AddField(
            model_name='devoirmatiere',
            name='numero_ordre',
            field=models.PositiveSmallIntegerField(default=1, help_text="Numéro d'ordre de passage de cette matière dans le programme", verbose_name='ordre dans le programme'),
        ),
        migrations.AddField(
            model_name='devoirmatiere',
            name='salle',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='salle / lieu'),
        ),
        migrations.AlterField(
            model_name='bulletindevoir',
            name='approuve_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bulletins_devoir_approuves', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='bulletindevoir',
            name='decision_conseil',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='décision du conseil'),
        ),
        migrations.AlterField(
            model_name='bulletindevoir',
            name='prof_lu',
            field=models.BooleanField(default=False, verbose_name='lu par le professeur principal'),
        ),
        migrations.AlterField(
            model_name='bulletindevoirligne',
            name='moyenne',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='moyenne du trimestre'),
        ),
        migrations.AlterField(
            model_name='bulletindevoirligne',
            name='note_devoir',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='note devoir surveillé'),
        ),
        migrations.AlterField(
            model_name='bulletindevoirligne',
            name='rang',
            field=models.PositiveIntegerField(default=0, verbose_name='rang dans la classe'),
        ),
        migrations.AlterField(
            model_name='devoirmatiere',
            name='corrige_type_file',
            field=models.FileField(blank=True, null=True, upload_to='devoirs/corriges/%Y/%m/', verbose_name='corrigé type'),
        ),
        migrations.AlterField(
            model_name='devoirmatiere',
            name='epreuve_file',
            field=models.FileField(blank=True, null=True, upload_to='devoirs/epreuves/%Y/%m/', verbose_name='épreuve'),
        ),
        migrations.AlterField(
            model_name='devoirmatiere',
            name='soumis_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devoirs_soumis', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='devoirmatiere',
            name='statut',
            field=models.CharField(choices=[('programme', "Programmé (en attente de l'épreuve)"), ('soumis', 'Épreuve soumise par le prof'), ('valide', "Validé par l'admin"), ('rejete', 'Rejeté — à corriger')], default='programme', max_length=20, verbose_name='statut'),
        ),
        migrations.AlterField(
            model_name='devoirmatiere',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='soumis le'),
        ),
        migrations.AlterField(
            model_name='devoirmatiere',
            name='validated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='validé le'),
        ),
    ]
