# Generated by Django 6.0.4 on 2026-05-22 18:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_organisation'),
        ('devoirs', '0006_restructuration_evaluations_beninois'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BulletinAnnuel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('annee_scolaire', models.CharField(default='2025-2026', max_length=20, verbose_name='année scolaire')),
                ('numero_ordre', models.CharField(blank=True, max_length=20, verbose_name="n° d'ordre")),
                ('moyenne_annuelle', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='moyenne générale annuelle')),
                ('rang_classe', models.PositiveIntegerField(blank=True, null=True, verbose_name='rang dans la classe')),
                ('effectif_total', models.PositiveIntegerField(blank=True, null=True, verbose_name='effectif de la classe')),
                ('mention', models.CharField(blank=True, choices=[('Excellent', 'Excellent'), ('Très Bien', 'Très Bien'), ('Bien', 'Bien'), ('Assez Bien', 'Assez Bien'), ('Passable', 'Passable'), ('Insuffisant', 'Insuffisant')], max_length=20, verbose_name='mention')),
                ('appreciation_generale', models.TextField(blank=True, verbose_name='appréciation générale')),
                ('decision_conseil', models.CharField(blank=True, max_length=200, verbose_name='décision du conseil de classe')),
                ('observations_chef', models.TextField(blank=True, verbose_name="observations du chef d'établissement")),
                ('absences_justifiees', models.PositiveSmallIntegerField(default=0, verbose_name='absences justifiées (h)')),
                ('absences_non_justifiees', models.PositiveSmallIntegerField(default=0, verbose_name='absences non justifiées (h)')),
                ('retards', models.PositiveSmallIntegerField(default=0, verbose_name='retards')),
                ('presente_examen', models.BooleanField(default=False, verbose_name="présenté(e) à l'examen")),
                ('resultat_examen', models.CharField(blank=True, max_length=50, verbose_name='résultat examen')),
                ('mention_examen', models.CharField(blank=True, max_length=50, verbose_name="mention à l'examen")),
                ('fait_a', models.CharField(blank=True, default='Cotonou', max_length=100, verbose_name='fait à')),
                ('date_emission', models.DateTimeField(blank=True, null=True, verbose_name="date d'émission")),
                ('file_pdf', models.FileField(blank=True, null=True, upload_to='bulletins_annuels/%Y/%m/', verbose_name='fichier PDF')),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon'), ('approuve', 'Approuvé'), ('publie', 'Publié')], default='brouillon', max_length=20, verbose_name='statut')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('classe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bulletins_annuels', to='core.classe', verbose_name='classe')),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bulletins_annuels', to=settings.AUTH_USER_MODEL, verbose_name='élève')),
            ],
            options={
                'verbose_name': 'bulletin annuel',
                'verbose_name_plural': 'bulletins annuels',
                'ordering': ['-annee_scolaire', 'eleve'],
                'unique_together': {('eleve', 'annee_scolaire')},
            },
        ),
        migrations.CreateModel(
            name='BulletinAnnuelLigne',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('matiere_nom', models.CharField(max_length=200, verbose_name='matière')),
                ('coefficient', models.PositiveSmallIntegerField(default=1, verbose_name='coefficient')),
                ('t1_moy_interros', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='T1 — moy. interros')),
                ('t1_note_devoir', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='T1 — note DS')),
                ('t1_note_compo', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='T1 — note compo')),
                ('t1_moyenne', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='T1 — moyenne')),
                ('t2_moy_interros', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='T2 — moy. interros')),
                ('t2_note_devoir', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='T2 — note DS')),
                ('t2_note_compo', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='T2 — note compo')),
                ('t2_moyenne', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='T2 — moyenne')),
                ('t3_moy_interros', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='T3 — moy. interros')),
                ('t3_note_devoir', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='T3 — note DS')),
                ('t3_note_compo', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='T3 — note compo')),
                ('t3_moyenne', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='T3 — moyenne')),
                ('moyenne_annuelle', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='moyenne annuelle')),
                ('note_ponderee_annuelle', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='note pondérée')),
                ('rang_classe', models.PositiveIntegerField(blank=True, null=True, verbose_name='rang')),
                ('appreciation', models.TextField(blank=True, default='', verbose_name='appréciation')),
                ('bulletin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='devoirs.bulletinannuel', verbose_name='bulletin annuel')),
            ],
            options={
                'verbose_name': 'ligne bulletin annuel',
                'verbose_name_plural': 'lignes bulletin annuel',
                'ordering': ['matiere_nom'],
                'unique_together': {('bulletin', 'matiere_nom')},
            },
        ),
        migrations.CreateModel(
            name='NoteTrimestre',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('matiere_nom', models.CharField(max_length=200, verbose_name='matière')),
                ('coefficient', models.PositiveSmallIntegerField(default=1, verbose_name='coefficient')),
                ('annee_scolaire', models.CharField(default='2025-2026', max_length=20, verbose_name='année scolaire')),
                ('trimestre', models.CharField(choices=[('T1', '1er Trimestre'), ('T2', '2ème Trimestre'), ('T3', '3ème Trimestre')], max_length=2, verbose_name='trimestre')),
                ('moy_interrogations', models.DecimalField(blank=True, decimal_places=2, help_text='Moyenne des interrogations du trimestre (/20)', max_digits=5, null=True, verbose_name='moyenne interrogations')),
                ('note_devoir', models.DecimalField(blank=True, decimal_places=2, help_text='Note du devoir surveillé (/20)', max_digits=5, null=True, verbose_name='note devoir surveillé (DS)')),
                ('note_composition', models.DecimalField(blank=True, decimal_places=2, help_text='Note de la composition trimestrielle (/20)', max_digits=5, null=True, verbose_name='note composition')),
                ('moyenne_trimestre', models.DecimalField(blank=True, decimal_places=2, help_text='Formule : (DS + 2×Composition) / 3', max_digits=5, null=True, verbose_name='moyenne du trimestre')),
                ('note_ponderee', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='note pondérée (moy × coeff)')),
                ('rang_classe', models.PositiveIntegerField(blank=True, null=True, verbose_name='rang')),
                ('moyenne_classe', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='moyenne de la classe')),
                ('appreciation', models.TextField(blank=True, default='', verbose_name='appréciation')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('classe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notes_trimestre', to='core.classe', verbose_name='classe')),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes_trimestre', to=settings.AUTH_USER_MODEL, verbose_name='élève')),
            ],
            options={
                'verbose_name': 'note trimestrielle',
                'verbose_name_plural': 'notes trimestrielles',
                'ordering': ['matiere_nom', 'trimestre'],
                'unique_together': {('eleve', 'matiere_nom', 'trimestre', 'annee_scolaire')},
            },
        ),
    ]
