# Generated by Django 6.0.4 on 2026-04-30 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulletins', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bulletin',
            name='decision_conseil',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='décision du conseil'),
        ),
        migrations.AddField(
            model_name='bulletin',
            name='effectif_total',
            field=models.PositiveIntegerField(default=0, verbose_name='effectif total'),
        ),
        migrations.AddField(
            model_name='bulletin',
            name='type_bulletin',
            field=models.CharField(choices=[('administratif', 'Administratif (Format Ministère)'), ('professionnel', 'Professionnel (Format Entreprise)')], default='administratif', max_length=20, verbose_name='type de bulletin'),
        ),
    ]
