# Generated by Django 6.0.4 on 2026-05-01 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulletins', '0002_bulletin_decision_conseil_bulletin_effectif_total_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bulletin',
            name='periode',
            field=models.CharField(choices=[('T1', '1er Trimestre'), ('T2', '2ème Trimestre'), ('T3', '3ème Trimestre'), ('S1', '1er Semestre'), ('S2', '2ème Semestre'), ('AN', 'Annuel'), ('QCM', 'Évaluation QCM')], max_length=5),
        ),
    ]
