# Generated by Django 6.0.4 on 2026-05-01 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulletins', '0003_alter_bulletin_periode'),
    ]

    operations = [
        migrations.AddField(
            model_name='bulletinligne',
            name='coefficient',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=4),
        ),
    ]
