# Generated by Django 6.0.4 on 2026-05-02 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulletins', '0004_bulletinligne_coefficient'),
    ]

    operations = [
        migrations.AddField(
            model_name='bulletin',
            name='absences',
            field=models.PositiveIntegerField(default=0, verbose_name='absences jours'),
        ),
        migrations.AddField(
            model_name='bulletin',
            name='comportement_assiduite',
            field=models.CharField(choices=[('Excellent', 'Excellent'), ('Passable', 'Passable'), ('Moyen', 'Moyen'), ('Mauvais', 'Mauvais')], default='Moyen', max_length=20),
        ),
        migrations.AddField(
            model_name='bulletin',
            name='comportement_discipline',
            field=models.CharField(choices=[('Excellent', 'Excellent'), ('Passable', 'Passable'), ('Moyen', 'Moyen'), ('Mauvais', 'Mauvais')], default='Moyen', max_length=20),
        ),
        migrations.AddField(
            model_name='bulletin',
            name='comportement_ponctualite',
            field=models.CharField(choices=[('Excellent', 'Excellent'), ('Passable', 'Passable'), ('Moyen', 'Moyen'), ('Mauvais', 'Mauvais')], default='Moyen', max_length=20),
        ),
        migrations.AddField(
            model_name='bulletin',
            name='comportement_travail',
            field=models.CharField(choices=[('Excellent', 'Excellent'), ('Passable', 'Passable'), ('Moyen', 'Moyen'), ('Mauvais', 'Mauvais')], default='Moyen', max_length=20),
        ),
        migrations.AddField(
            model_name='bulletin',
            name='heures_absences',
            field=models.PositiveIntegerField(default=0, verbose_name="heures d'absence"),
        ),
        migrations.AddField(
            model_name='bulletin',
            name='minutes_retard',
            field=models.PositiveIntegerField(default=0, verbose_name='minutes de retard'),
        ),
        migrations.AddField(
            model_name='bulletin',
            name='observation_conseil',
            field=models.TextField(blank=True, default='', verbose_name='observation du conseil'),
        ),
        migrations.AddField(
            model_name='bulletin',
            name='retards',
            field=models.PositiveIntegerField(default=0, verbose_name='retards'),
        ),
        migrations.AddField(
            model_name='bulletinligne',
            name='controle',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='note controle'),
        ),
        migrations.AddField(
            model_name='bulletinligne',
            name='devoir',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='note devoir'),
        ),
        migrations.AddField(
            model_name='bulletinligne',
            name='note_moy_coeff',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='moy * coeff'),
        ),
        migrations.AddField(
            model_name='bulletinligne',
            name='rang',
            field=models.PositiveIntegerField(default=0, verbose_name='rang'),
        ),
    ]
