# Generated by Django 6.0.4 on 2026-05-03 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulletins', '0005_bulletin_absences_bulletin_comportement_assiduite_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bulletin',
            name='type_bulletin',
            field=models.CharField(choices=[('administratif', 'Administratif (Format Ministère)'), ('professionnel', 'Professionnel (Format Entreprise)'), ('qcm', 'QCM (Test de Connaissances)')], default='administratif', max_length=20, verbose_name='type de bulletin'),
        ),
    ]
