# Generated by Django 6.0.4 on 2026-05-11 07:49

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulletins', '0007_alter_bulletin_eleve'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bulletin',
            name='verification_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
