# Generated by Django 6.0.4 on 2026-05-12 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bulletins', '0008_alter_bulletin_verification_token'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bulletinligne',
            options={'ordering': ['matiere'], 'verbose_name': 'ligne de bulletin', 'verbose_name_plural': 'lignes de bulletin'},
        ),
    ]
