# Generated by Django 5.2.13 on 2026-05-14 07:15

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bulletins', '0009_alter_bulletinligne_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bulletin',
            options={'ordering': ['-created_at'], 'verbose_name': 'Bulletin', 'verbose_name_plural': 'Bulletins'},
        ),
    ]
