# Generated by Django 5.2.13 on 2026-05-14 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bulletins', '0010_alter_bulletin_options_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bulletin',
            unique_together=set(),
        ),
    ]
