# Generated by Django 5.2.13 on 2026-05-15 09:46

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulletins', '0011_alter_bulletin_unique_together'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BulletinTokenPartage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token', models.UUIDField(default=uuid.uuid4, unique=True, verbose_name='token')),
                ('expire_at', models.DateTimeField(verbose_name='expire le')),
                ('nb_consultations_max', models.PositiveSmallIntegerField(default=3, verbose_name='consultations max')),
                ('nb_consultations', models.PositiveSmallIntegerField(default=0, verbose_name='consultations effectuées')),
                ('est_actif', models.BooleanField(default=True, verbose_name='actif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bulletin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tokens_partage', to='bulletins.bulletin')),
                ('cree_par', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tokens_bulletin_crees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'token de partage bulletin',
                'verbose_name_plural': 'tokens de partage bulletins',
            },
        ),
        migrations.CreateModel(
            name='BulletinAccesLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type_acces', models.CharField(choices=[('consultation', 'Consultation'), ('telechargement', 'Téléchargement PDF'), ('impression', 'Impression'), ('partage', 'Partage'), ('approbation', 'Approbation'), ('revocation', 'Révocation')], max_length=20, verbose_name="type d'accès")),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='adresse IP')),
                ('user_agent', models.TextField(blank=True, verbose_name='user agent')),
                ('succes', models.BooleanField(default=True, verbose_name='accès autorisé')),
                ('acces_at', models.DateTimeField(auto_now_add=True)),
                ('accede_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bulletins_accedes', to=settings.AUTH_USER_MODEL)),
                ('bulletin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acces_logs', to='bulletins.bulletin')),
            ],
            options={
                'verbose_name': "log d'accès bulletin",
                'verbose_name_plural': "logs d'accès bulletins",
                'ordering': ['-acces_at'],
                'indexes': [models.Index(fields=['bulletin', 'acces_at'], name='bulletins_b_bulleti_1aadf6_idx'), models.Index(fields=['accede_par', 'acces_at'], name='bulletins_b_accede__3a7968_idx')],
            },
        ),
    ]
