# Generated by Django 5.2.13 on 2026-05-15 09:46

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certifications', '0003_initial'),
        ('subscriptions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='acces_certificats',
            field=models.BooleanField(default=False, verbose_name='certificats accessibles'),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='acces_classes_virtuelles',
            field=models.BooleanField(default=False, verbose_name='classes virtuelles accessibles'),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='acces_correction_ia',
            field=models.BooleanField(default=False, verbose_name='correction IA accessible'),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='acces_cours_pct',
            field=models.PositiveSmallIntegerField(default=100, help_text='Pourcentage des cours accessibles. 20 pour le forfait gratuit.', verbose_name='accès cours (%)'),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='acces_examens_blancs',
            field=models.BooleanField(default=False, verbose_name='examens blancs accessibles'),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='acces_forum_general',
            field=models.BooleanField(default=True, verbose_name='forum général accessible'),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='acces_quiz_basique',
            field=models.BooleanField(default=True, verbose_name='quiz de base accessibles'),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='acces_suivi_personnalise',
            field=models.BooleanField(default=False, verbose_name='suivi personnalisé accessible'),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='duree',
            field=models.CharField(choices=[('illimite', 'Illimité (Gratuit)'), ('mensuel', 'Mensuel (30 jours)'), ('trimestriel', 'Trimestriel (90 jours)'), ('annuel', 'Annuel (365 jours)')], default='mensuel', max_length=15),
        ),
        migrations.CreateModel(
            name='AtelierThematique',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titre', models.CharField(max_length=300, verbose_name="titre de l'atelier")),
                ('description', models.TextField()),
                ('date_debut', models.DateTimeField(verbose_name='date de début')),
                ('date_fin', models.DateTimeField(verbose_name='date de fin')),
                ('nb_places_max', models.PositiveSmallIntegerField(default=20, verbose_name='places maximum')),
                ('lien_visio', models.URLField(blank=True, verbose_name='lien visioconférence')),
                ('support_file', models.FileField(blank=True, null=True, upload_to='ateliers/supports/%Y/%m/', verbose_name='support de cours')),
                ('prix', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='prix (XOF)')),
                ('statut', models.CharField(choices=[('planifie', 'Planifié'), ('ouvert', 'Inscriptions ouvertes'), ('complet', 'Complet'), ('en_cours', 'En cours'), ('termine', 'Terminé'), ('annule', 'Annulé')], default='planifie', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('animateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ateliers_animes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'atelier thématique',
                'verbose_name_plural': 'ateliers thématiques',
                'ordering': ['-date_debut'],
            },
        ),
        migrations.CreateModel(
            name='BourseEtudes',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('financeur', models.CharField(max_length=300, verbose_name='financeur / partenaire')),
                ('couverture_pct', models.PositiveSmallIntegerField(default=100, help_text='100 = entièrement gratuit', verbose_name='couverture (%)')),
                ('montant_restant_a_payer', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='montant restant (XOF)')),
                ('motif_demande', models.TextField(verbose_name='motif de la demande')),
                ('pieces_jointes', models.JSONField(blank=True, default=list, verbose_name='pièces jointes')),
                ('statut', models.CharField(choices=[('en_attente', 'Demande en attente'), ('approuvee', 'Approuvée'), ('refusee', 'Refusée'), ('active', 'Active'), ('expiree', 'Expirée')], default='en_attente', max_length=15)),
                ('commentaire_admin', models.TextField(blank=True)),
                ('date_debut', models.DateField(blank=True, null=True, verbose_name='début de la bourse')),
                ('date_fin', models.DateField(blank=True, null=True, verbose_name='fin de la bourse')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approuve_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bourses_approuvees', to=settings.AUTH_USER_MODEL)),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bourses_etudes', to=settings.AUTH_USER_MODEL)),
                ('plan_offert', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bourses', to='subscriptions.subscriptionplan')),
            ],
            options={
                'verbose_name': "bourse d'études",
                'verbose_name_plural': "bourses d'études",
            },
        ),
        migrations.CreateModel(
            name='CertificationTransversale',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('intitule', models.CharField(max_length=300, verbose_name='intitulé de la certification')),
                ('competences', models.JSONField(default=list, verbose_name='compétences évaluées')),
                ('niveau', models.CharField(choices=[('debutant', 'Débutant'), ('intermediaire', 'Intermédiaire'), ('avance', 'Avancé'), ('expert', 'Expert')], default='intermediaire', max_length=15)),
                ('score_obtenu', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='score obtenu (%)')),
                ('seuil_validation', models.DecimalField(decimal_places=2, default=70.0, max_digits=5, verbose_name='seuil de validation (%)')),
                ('statut', models.CharField(choices=[('en_cours', 'Parcours en cours'), ('evaluation_pending', "En attente d'évaluation"), ('certifie', 'Certifié'), ('echoue', 'Non validé')], default='en_cours', max_length=25)),
                ('date_debut', models.DateField(blank=True, null=True, verbose_name='début du parcours')),
                ('date_certification', models.DateField(blank=True, null=True, verbose_name='date de certification')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('certificat', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certification_transversale', to='certifications.certificate')),
                ('delivre_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certifications_transversales_delivrees', to=settings.AUTH_USER_MODEL)),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certifications_transversales', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'certification transversale',
                'verbose_name_plural': 'certifications transversales',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CoachingIndividuel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type_coaching', models.CharField(choices=[('academique', 'Coaching académique (matière)'), ('methodologie', 'Méthodologie de travail'), ('orientation', 'Orientation scolaire'), ('psychologique', 'Gestion du stress / bien-être'), ('technique', 'Coaching technique (numérique)')], default='academique', max_length=20)),
                ('titre', models.CharField(max_length=200, verbose_name='titre de la session')),
                ('description', models.TextField(blank=True)),
                ('date_session', models.DateTimeField(verbose_name='date et heure')),
                ('duree_minutes', models.PositiveIntegerField(default=60, verbose_name='durée (minutes)')),
                ('lien_visio', models.URLField(blank=True, verbose_name='lien visioconférence')),
                ('prix', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='prix (XOF)')),
                ('est_paye', models.BooleanField(default=False, verbose_name='payé')),
                ('statut', models.CharField(choices=[('disponible', 'Disponible à la réservation'), ('reserve', 'Réservé'), ('confirme', 'Confirmé'), ('en_cours', 'En cours'), ('termine', 'Terminé'), ('annule', 'Annulé')], default='disponible', max_length=15)),
                ('notes_coach', models.TextField(blank=True, verbose_name='notes du coach (privées)')),
                ('compte_rendu', models.TextField(blank=True, verbose_name='compte-rendu partagé')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions_coaching_animees', to=settings.AUTH_USER_MODEL)),
                ('eleve', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions_coaching_suivies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'coaching individuel',
                'verbose_name_plural': 'coachings individuels',
                'ordering': ['-date_session'],
            },
        ),
        migrations.CreateModel(
            name='InscriptionAtelier',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('est_paye', models.BooleanField(default=False, verbose_name='payé')),
                ('present', models.BooleanField(default=False, verbose_name='présent')),
                ('inscrit_at', models.DateTimeField(auto_now_add=True)),
                ('atelier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subscriptions.atelierthematique')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'inscription atelier',
                'verbose_name_plural': 'inscriptions ateliers',
                'unique_together': {('atelier', 'participant')},
            },
        ),
        migrations.AddField(
            model_name='atelierthematique',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='ateliers_inscrits', through='subscriptions.InscriptionAtelier', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='LicenceEcole',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('etablissement', models.CharField(max_length=300, verbose_name="nom de l'établissement")),
                ('contact_nom', models.CharField(max_length=200, verbose_name='nom du contact')),
                ('contact_email', models.EmailField(max_length=254, verbose_name='email de contact')),
                ('contact_tel', models.CharField(blank=True, max_length=20, verbose_name='téléphone')),
                ('nb_eleves_max', models.PositiveIntegerField(verbose_name="nombre d'élèves maximum")),
                ('nb_eleves_actifs', models.PositiveIntegerField(default=0, verbose_name='élèves actuellement actifs')),
                ('prix_par_eleve', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='prix par élève (XOF)')),
                ('remise_pct', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='remise (%)')),
                ('date_debut', models.DateField(verbose_name='date de début')),
                ('date_fin', models.DateField(verbose_name='date de fin')),
                ('statut', models.CharField(choices=[('en_attente', 'En attente de validation'), ('active', 'Active'), ('suspendue', 'Suspendue'), ('expiree', 'Expirée')], default='en_attente', max_length=15)),
                ('code_acces', models.CharField(blank=True, max_length=20, unique=True, verbose_name="code d'accès école")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='licences_ecoles', to='subscriptions.subscriptionplan')),
            ],
            options={
                'verbose_name': 'licence école',
                'verbose_name_plural': 'licences écoles',
            },
        ),
    ]
