# Generated by Django 5.2.13 on 2026-05-15 11:27

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_subscriptionplan_acces_certificats_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigurationPaywall',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titre_accroche', models.CharField(default='Votre correction est prête… mais elle est verrouillée 🔒', max_length=200, verbose_name="titre d'accroche")),
                ('sous_titre', models.CharField(default='Débloquez votre note complète et vos conseils personnalisés en quelques secondes.', max_length=300, verbose_name='sous-titre')),
                ('badge_urgence', models.CharField(blank=True, default='⚡ Offre limitée · Résultats disponibles maintenant', max_length=100, verbose_name='badge urgence')),
                ('pourcentage_apercu', models.PositiveSmallIntegerField(default=30, help_text='Pourcentage des détails de correction montrés avant le paywall (0–100)', verbose_name='aperçu gratuit (%)')),
                ('prix_correction_unitaire', models.DecimalField(decimal_places=0, default=500, max_digits=10, verbose_name='prix correction unitaire (XOF)')),
                ('label_correction_unitaire', models.CharField(default='Débloquer cette correction', max_length=100, verbose_name='libellé correction unitaire')),
                ('description_correction_unitaire', models.TextField(default="Accès immédiat à votre note, vos points forts, vos axes d'amélioration et votre bulletin PDF.", verbose_name='description correction unitaire')),
                ('label_btn_abonnement', models.CharField(default='Passer en version Pro — corrections illimitées', max_length=100, verbose_name='libellé bouton abonnement')),
                ('is_actif', models.BooleanField(default=True, verbose_name='paywall actif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuration Paywall Correction IA',
                'verbose_name_plural': 'Configuration Paywall Correction IA',
            },
        ),
    ]
