# Generated by Django 6.0.4 on 2026-05-11 12:27

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exams', '0004_exam_rejection_comment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bareme',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titre', models.CharField(blank=True, max_length=300, verbose_name='titre')),
                ('total_points', models.DecimalField(decimal_places=2, default=20, max_digits=5, verbose_name='total points')),
                ('donnees', models.JSONField(default=dict, verbose_name='données barème')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cree_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='baremes_crees', to=settings.AUTH_USER_MODEL, verbose_name='créé par')),
                ('exam', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bareme', to='exams.exam', verbose_name='épreuve')),
            ],
            options={
                'verbose_name': 'barème',
                'verbose_name_plural': 'barèmes',
                'ordering': ['-created_at'],
            },
        ),
    ]
