# Generated by Django 6.0.4 on 2026-05-12 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_emailqueue_corps_html_emailqueue_corps_texte_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emailqueue',
            options={'ordering': ['-created_at'], 'verbose_name': 'Email en attente', 'verbose_name_plural': 'Emails en attente'},
        ),
        migrations.AlterModelOptions(
            name='globalannouncement',
            options={'ordering': ['-created_at'], 'verbose_name': 'Annonce globale', 'verbose_name_plural': 'Annonces globales'},
        ),
    ]
