# Generated by Django 6.0.4 on 2026-05-11 07:09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schools', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Absence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_debut', models.DateField(verbose_name='date de début')),
                ('date_fin', models.DateField(blank=True, null=True, verbose_name='date de fin')),
                ('duree_jours', models.PositiveIntegerField(blank=True, null=True, verbose_name='durée (jours)')),
                ('type_absence', models.CharField(choices=[('maladie', 'Maladie'), ('familiale', 'Raison familiale'), ('academique', 'Motif académique'), ('disciplinaire', 'Motif disciplinaire'), ('autre', 'Autre')], max_length=20, verbose_name="type d'absence")),
                ('statut', models.CharField(choices=[('en_cours', 'En cours'), ('justifiee', 'Justifiée'), ('non_justifiee', 'Non justifiée'), ('annulee', 'Annulée')], default='en_cours', max_length=20, verbose_name='statut')),
                ('motif', models.TextField(verbose_name='motif')),
                ('justificatif', models.FileField(blank=True, null=True, upload_to='attendance/absences/', verbose_name='justificatif')),
                ('date_justification', models.DateField(blank=True, null=True, verbose_name='date de justification')),
                ('cours_manques', models.PositiveIntegerField(default=0, verbose_name='cours manqués')),
                ('evaluations_manquees', models.PositiveIntegerField(default=0, verbose_name='évaluations manquées')),
                ('observations', models.TextField(blank=True, verbose_name='observations')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='absences', to='schools.classe')),
                ('eleve', models.ForeignKey(limit_choices_to={'role': 'eleve'}, on_delete=django.db.models.deletion.CASCADE, related_name='absences', to=settings.AUTH_USER_MODEL)),
                ('valide_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='absences_validees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Absence',
                'verbose_name_plural': 'Absences',
                'ordering': ['-date_debut'],
            },
        ),
        migrations.CreateModel(
            name='RapportPresence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type_rapport', models.CharField(choices=[('mensuel', 'Mensuel'), ('trimestriel', 'Trimestriel'), ('annuel', 'Annuel'), ('personnalise', 'Personnalisé')], max_length=20, verbose_name='type de rapport')),
                ('periode_debut', models.DateField(verbose_name='début de période')),
                ('periode_fin', models.DateField(verbose_name='fin de période')),
                ('total_jours', models.PositiveIntegerField(verbose_name='total jours')),
                ('jours_presents', models.PositiveIntegerField(verbose_name='jours présents')),
                ('jours_absents', models.PositiveIntegerField(verbose_name='jours absents')),
                ('jours_retards', models.PositiveIntegerField(verbose_name='jours retards')),
                ('taux_presence', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='taux de présence (%)')),
                ('absences_justifiees', models.PositiveIntegerField(default=0, verbose_name='absences justifiées')),
                ('absences_non_justifiees', models.PositiveIntegerField(default=0, verbose_name='absences non justifiées')),
                ('commentaire', models.TextField(blank=True, verbose_name='commentaire')),
                ('recommandation', models.TextField(blank=True, verbose_name='recommandation')),
                ('date_generation', models.DateTimeField(auto_now_add=True)),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rapports_presence', to='schools.classe')),
                ('eleve', models.ForeignKey(limit_choices_to={'role': 'eleve'}, on_delete=django.db.models.deletion.CASCADE, related_name='rapports_presence', to=settings.AUTH_USER_MODEL)),
                ('genere_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rapports_presence_generes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Rapport de présence',
                'verbose_name_plural': 'Rapports de présence',
                'ordering': ['-periode_fin'],
            },
        ),
        migrations.CreateModel(
            name='Retard',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(verbose_name='date')),
                ('heure_prevue', models.TimeField(verbose_name='heure prévue')),
                ('heure_arrivee', models.TimeField(verbose_name="heure d'arrivée")),
                ('minutes_retard', models.PositiveIntegerField(verbose_name='minutes de retard')),
                ('type_retard', models.CharField(choices=[('matin', 'Retard matin'), ('apres_midi', 'Retard après-midi'), ('cours', 'Retard en cours'), ('reunion', 'Retard réunion')], max_length=20, verbose_name='type de retard')),
                ('motif', models.TextField(blank=True, verbose_name='motif')),
                ('sanction', models.TextField(blank=True, verbose_name='sanction')),
                ('est_pardonne', models.BooleanField(default=False, verbose_name='pardonné')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retards', to='schools.classe')),
                ('eleve', models.ForeignKey(limit_choices_to={'role': 'eleve'}, on_delete=django.db.models.deletion.CASCADE, related_name='retards', to=settings.AUTH_USER_MODEL)),
                ('signale_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='retards_signales', to=settings.AUTH_USER_MODEL)),
                ('valide_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='retards_validees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Retard',
                'verbose_name_plural': 'Retards',
                'ordering': ['-date', '-minutes_retard'],
            },
        ),
        migrations.CreateModel(
            name='Presence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(verbose_name='date')),
                ('heure_arrivee', models.TimeField(blank=True, null=True, verbose_name="heure d'arrivée")),
                ('statut', models.CharField(choices=[('present', 'Présent'), ('absent', 'Absent'), ('retard', 'Retard'), ('excuse', 'Excusé'), ('malade', 'Malade')], default='present', max_length=20, verbose_name='statut')),
                ('motif_absence', models.TextField(blank=True, verbose_name="motif d'absence")),
                ('duree_absence', models.PositiveIntegerField(blank=True, null=True, verbose_name="durée d'absence (heures)")),
                ('minutes_retard', models.PositiveIntegerField(default=0, verbose_name='minutes de retard')),
                ('est_justifie', models.BooleanField(default=False, verbose_name='justifié')),
                ('justificatif', models.FileField(blank=True, null=True, upload_to='attendance/justificatifs/', verbose_name='justificatif')),
                ('date_justification', models.DateField(blank=True, null=True, verbose_name='date de justification')),
                ('observations', models.TextField(blank=True, verbose_name='observations')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presences', to='schools.classe')),
                ('eleve', models.ForeignKey(limit_choices_to={'role': 'eleve'}, on_delete=django.db.models.deletion.CASCADE, related_name='presences', to=settings.AUTH_USER_MODEL)),
                ('professeur', models.ForeignKey(limit_choices_to={'role': 'professeur'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='presences_signees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Présence',
                'verbose_name_plural': 'Présences',
                'ordering': ['-date', 'eleve__last_name'],
                'unique_together': {('eleve', 'classe', 'date')},
            },
        ),
        migrations.CreateModel(
            name='PresenceProfesseur',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(verbose_name='date')),
                ('heure_arrivee', models.TimeField(blank=True, null=True, verbose_name="heure d'arrivée")),
                ('heure_depart', models.TimeField(blank=True, null=True, verbose_name='heure de départ')),
                ('statut', models.CharField(choices=[('present', 'Présent'), ('absent', 'Absent'), ('retard', 'Retard'), ('mission', 'En mission')], default='present', max_length=20, verbose_name='statut')),
                ('motif_absence', models.TextField(blank=True, verbose_name="motif d'absence")),
                ('minutes_retard', models.PositiveIntegerField(default=0, verbose_name='minutes de retard')),
                ('observations', models.TextField(blank=True, verbose_name='observations')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('professeur', models.ForeignKey(limit_choices_to={'role': 'professeur'}, on_delete=django.db.models.deletion.CASCADE, related_name='presences_prof', to=settings.AUTH_USER_MODEL)),
                ('valide_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='presences_validees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Présence professeur',
                'verbose_name_plural': 'Présences professeurs',
                'ordering': ['-date'],
                'unique_together': {('professeur', 'date')},
            },
        ),
    ]
