# Generated by Django 5.2.13 on 2026-05-14 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presence',
            name='date',
            field=models.DateField(db_index=True, verbose_name='date'),
        ),
        migrations.AlterField(
            model_name='presence',
            name='statut',
            field=models.CharField(choices=[('present', 'Présent'), ('absent', 'Absent'), ('retard', 'Retard'), ('excuse', 'Excusé'), ('malade', 'Malade')], db_index=True, default='present', max_length=20, verbose_name='statut'),
        ),
    ]
